// GENERATED by scripts/gen-bindings.mjs. Converters between the definition structs and plain JavaScript objects.
#pragma once
#include <box2d/box2d.h>
#include <emscripten/val.h>
#include <string>

emscripten::val b2JointDefToJS(const b2JointDef& d);
void b2JointDefApply(b2JointDef& d, emscripten::val o);
emscripten::val b2WorldDefToJS(const b2WorldDef& d);
void b2WorldDefApply(b2WorldDef& d, emscripten::val o);
b2WorldDef b2WorldDefFromJS(emscripten::val o);
emscripten::val b2BodyDefToJS(const b2BodyDef& d);
void b2BodyDefApply(b2BodyDef& d, emscripten::val o);
b2BodyDef b2BodyDefFromJS(emscripten::val o);
emscripten::val b2FilterToJS(const b2Filter& d);
void b2FilterApply(b2Filter& d, emscripten::val o);
b2Filter b2FilterFromJS(emscripten::val o);
emscripten::val b2QueryFilterToJS(const b2QueryFilter& d);
void b2QueryFilterApply(b2QueryFilter& d, emscripten::val o);
b2QueryFilter b2QueryFilterFromJS(emscripten::val o);
emscripten::val b2SurfaceMaterialToJS(const b2SurfaceMaterial& d);
void b2SurfaceMaterialApply(b2SurfaceMaterial& d, emscripten::val o);
b2SurfaceMaterial b2SurfaceMaterialFromJS(emscripten::val o);
emscripten::val b2ShapeDefToJS(const b2ShapeDef& d);
void b2ShapeDefApply(b2ShapeDef& d, emscripten::val o);
b2ShapeDef b2ShapeDefFromJS(emscripten::val o);
emscripten::val b2ChainDefToJS(const b2ChainDef& d);
void b2ChainDefApply(b2ChainDef& d, emscripten::val o);
b2ChainDef b2ChainDefFromJS(emscripten::val o);
emscripten::val b2DistanceJointDefToJS(const b2DistanceJointDef& d);
void b2DistanceJointDefApply(b2DistanceJointDef& d, emscripten::val o);
b2DistanceJointDef b2DistanceJointDefFromJS(emscripten::val o);
emscripten::val b2MotorJointDefToJS(const b2MotorJointDef& d);
void b2MotorJointDefApply(b2MotorJointDef& d, emscripten::val o);
b2MotorJointDef b2MotorJointDefFromJS(emscripten::val o);
emscripten::val b2FilterJointDefToJS(const b2FilterJointDef& d);
void b2FilterJointDefApply(b2FilterJointDef& d, emscripten::val o);
b2FilterJointDef b2FilterJointDefFromJS(emscripten::val o);
emscripten::val b2PrismaticJointDefToJS(const b2PrismaticJointDef& d);
void b2PrismaticJointDefApply(b2PrismaticJointDef& d, emscripten::val o);
b2PrismaticJointDef b2PrismaticJointDefFromJS(emscripten::val o);
emscripten::val b2RevoluteJointDefToJS(const b2RevoluteJointDef& d);
void b2RevoluteJointDefApply(b2RevoluteJointDef& d, emscripten::val o);
b2RevoluteJointDef b2RevoluteJointDefFromJS(emscripten::val o);
emscripten::val b2WeldJointDefToJS(const b2WeldJointDef& d);
void b2WeldJointDefApply(b2WeldJointDef& d, emscripten::val o);
b2WeldJointDef b2WeldJointDefFromJS(emscripten::val o);
emscripten::val b2WheelJointDefToJS(const b2WheelJointDef& d);
void b2WheelJointDefApply(b2WheelJointDef& d, emscripten::val o);
b2WheelJointDef b2WheelJointDefFromJS(emscripten::val o);
emscripten::val b2ExplosionDefToJS(const b2ExplosionDef& d);
void b2ExplosionDefApply(b2ExplosionDef& d, emscripten::val o);
b2ExplosionDef b2ExplosionDefFromJS(emscripten::val o);
emscripten::val b2DebugDrawToJS(const b2DebugDraw& d);
void b2DebugDrawApply(b2DebugDraw& d, emscripten::val o);
b2DebugDraw b2DebugDrawFromJS(emscripten::val o);
