// GENERATED by scripts/gen-bindings.mjs from box2d/include/box2d/*.h. Do not edit; run `npm run gen`.
#include "glue.h"

using namespace emscripten;

// ---- accessors for array, count, 64-bit and pointer fields ----
static val get_b2ShapeProxy_points(const b2ShapeProxy& s) { return arrayToVal(s.points, std::min(static_cast<int>(s.count), static_cast<int>(std::size(s.points)))); }
static void set_b2ShapeProxy_points(b2ShapeProxy& s, val v) { valToArray(v, s.points, static_cast<int>(std::size(s.points))); }
static int get_b2ShapeProxy_count(const b2ShapeProxy& s) { return s.count; }
static void set_b2ShapeProxy_count(b2ShapeProxy& s, int v) { s.count = v < 0 ? 0 : (v > static_cast<int>(std::size(s.points)) ? static_cast<int>(std::size(s.points)) : v); }
static val get_b2Polygon_vertices(const b2Polygon& s) { return arrayToVal(s.vertices, std::min(static_cast<int>(s.count), static_cast<int>(std::size(s.vertices)))); }
static void set_b2Polygon_vertices(b2Polygon& s, val v) { valToArray(v, s.vertices, static_cast<int>(std::size(s.vertices))); }
static val get_b2Polygon_normals(const b2Polygon& s) { return arrayToVal(s.normals, std::min(static_cast<int>(s.count), static_cast<int>(std::size(s.normals)))); }
static void set_b2Polygon_normals(b2Polygon& s, val v) { valToArray(v, s.normals, static_cast<int>(std::size(s.normals))); }
static int get_b2Polygon_count(const b2Polygon& s) { return s.count; }
static void set_b2Polygon_count(b2Polygon& s, int v) { s.count = v < 0 ? 0 : (v > std::min(static_cast<int>(std::size(s.vertices)), static_cast<int>(std::size(s.normals))) ? std::min(static_cast<int>(std::size(s.vertices)), static_cast<int>(std::size(s.normals))) : v); }
static val get_b2Hull_points(const b2Hull& s) { return arrayToVal(s.points, std::min(static_cast<int>(s.count), static_cast<int>(std::size(s.points)))); }
static void set_b2Hull_points(b2Hull& s, val v) { valToArray(v, s.points, static_cast<int>(std::size(s.points))); }
static int get_b2Hull_count(const b2Hull& s) { return s.count; }
static void set_b2Hull_count(b2Hull& s, int v) { s.count = v < 0 ? 0 : (v > static_cast<int>(std::size(s.points)) ? static_cast<int>(std::size(s.points)) : v); }
static val get_b2SimplexCache_indexA(const b2SimplexCache& s) { return arrayToVal(s.indexA, static_cast<int>(std::size(s.indexA))); }
static void set_b2SimplexCache_indexA(b2SimplexCache& s, val v) { valToArray(v, s.indexA, static_cast<int>(std::size(s.indexA))); }
static val get_b2SimplexCache_indexB(const b2SimplexCache& s) { return arrayToVal(s.indexB, static_cast<int>(std::size(s.indexB))); }
static void set_b2SimplexCache_indexB(b2SimplexCache& s, val v) { valToArray(v, s.indexB, static_cast<int>(std::size(s.indexB))); }
static val get_b2Manifold_points(const b2Manifold& s) { return arrayToVal(s.points, std::min(static_cast<int>(s.pointCount), static_cast<int>(std::size(s.points)))); }
static void set_b2Manifold_points(b2Manifold& s, val v) { valToArray(v, s.points, static_cast<int>(std::size(s.points))); }
static int get_b2Manifold_pointCount(const b2Manifold& s) { return s.pointCount; }
static void set_b2Manifold_pointCount(b2Manifold& s, int v) { s.pointCount = v < 0 ? 0 : (v > static_cast<int>(std::size(s.points)) ? static_cast<int>(std::size(s.points)) : v); }
static val get_b2Counters_colorCounts(const b2Counters& s) { return arrayToVal(s.colorCounts, static_cast<int>(std::size(s.colorCounts))); }
static void set_b2Counters_colorCounts(b2Counters& s, val v) { valToArray(v, s.colorCounts, static_cast<int>(std::size(s.colorCounts))); }
static uint32_t get_b2BodyMoveEvent_userData(const b2BodyMoveEvent& s) { return toInt(s.userData); }
static void set_b2BodyMoveEvent_userData(b2BodyMoveEvent& s, uint32_t v) { s.userData = fromInt(v); }
static uint32_t get_b2JointEvent_userData(const b2JointEvent& s) { return toInt(s.userData); }
static void set_b2JointEvent_userData(b2JointEvent& s, uint32_t v) { s.userData = fromInt(v); }

// ---- definition struct converters ----
val b2JointDefToJS(const b2JointDef& d) {
    val o = val::object();
    o.set("bodyIdA", d.bodyIdA);
    o.set("bodyIdB", d.bodyIdB);
    o.set("localFrameA", d.localFrameA);
    o.set("localFrameB", d.localFrameB);
    o.set("forceThreshold", d.forceThreshold);
    o.set("torqueThreshold", d.torqueThreshold);
    o.set("constraintHertz", d.constraintHertz);
    o.set("constraintDampingRatio", d.constraintDampingRatio);
    o.set("drawScale", d.drawScale);
    o.set("collideConnected", d.collideConnected);
    return o;
}

void b2JointDefApply(b2JointDef& d, val o) {
    if (!o["bodyIdA"].isUndefined()) d.bodyIdA = o["bodyIdA"].as<b2BodyId>();
    if (!o["bodyIdB"].isUndefined()) d.bodyIdB = o["bodyIdB"].as<b2BodyId>();
    if (!o["localFrameA"].isUndefined()) d.localFrameA = o["localFrameA"].as<b2Transform>();
    if (!o["localFrameB"].isUndefined()) d.localFrameB = o["localFrameB"].as<b2Transform>();
    if (!o["forceThreshold"].isUndefined()) d.forceThreshold = o["forceThreshold"].as<float>();
    if (!o["torqueThreshold"].isUndefined()) d.torqueThreshold = o["torqueThreshold"].as<float>();
    if (!o["constraintHertz"].isUndefined()) d.constraintHertz = o["constraintHertz"].as<float>();
    if (!o["constraintDampingRatio"].isUndefined()) d.constraintDampingRatio = o["constraintDampingRatio"].as<float>();
    if (!o["drawScale"].isUndefined()) d.drawScale = o["drawScale"].as<float>();
    if (!o["collideConnected"].isUndefined()) d.collideConnected = o["collideConnected"].as<bool>();
}

val b2WorldDefToJS(const b2WorldDef& d) {
    val o = val::object();
    o.set("gravity", d.gravity);
    o.set("restitutionThreshold", d.restitutionThreshold);
    o.set("hitEventThreshold", d.hitEventThreshold);
    o.set("contactHertz", d.contactHertz);
    o.set("contactDampingRatio", d.contactDampingRatio);
    o.set("contactSpeed", d.contactSpeed);
    o.set("maximumLinearSpeed", d.maximumLinearSpeed);
    o.set("enableSleep", d.enableSleep);
    o.set("enableContinuous", d.enableContinuous);
    o.set("enableContactSoftening", d.enableContactSoftening);
    return o;
}

void b2WorldDefApply(b2WorldDef& d, val o) {
    if (!o["gravity"].isUndefined()) d.gravity = o["gravity"].as<b2Vec2>();
    if (!o["restitutionThreshold"].isUndefined()) d.restitutionThreshold = o["restitutionThreshold"].as<float>();
    if (!o["hitEventThreshold"].isUndefined()) d.hitEventThreshold = o["hitEventThreshold"].as<float>();
    if (!o["contactHertz"].isUndefined()) d.contactHertz = o["contactHertz"].as<float>();
    if (!o["contactDampingRatio"].isUndefined()) d.contactDampingRatio = o["contactDampingRatio"].as<float>();
    if (!o["contactSpeed"].isUndefined()) d.contactSpeed = o["contactSpeed"].as<float>();
    if (!o["maximumLinearSpeed"].isUndefined()) d.maximumLinearSpeed = o["maximumLinearSpeed"].as<float>();
    if (!o["enableSleep"].isUndefined()) d.enableSleep = o["enableSleep"].as<bool>();
    if (!o["enableContinuous"].isUndefined()) d.enableContinuous = o["enableContinuous"].as<bool>();
    if (!o["enableContactSoftening"].isUndefined()) d.enableContactSoftening = o["enableContactSoftening"].as<bool>();
}

b2WorldDef b2WorldDefFromJS(val o) {
    b2WorldDef d = b2DefaultWorldDef();
    b2WorldDefApply(d, o);
    return d;
}

val b2BodyDefToJS(const b2BodyDef& d) {
    val o = val::object();
    o.set("type", d.type);
    o.set("position", d.position);
    o.set("rotation", d.rotation);
    o.set("linearVelocity", d.linearVelocity);
    o.set("angularVelocity", d.angularVelocity);
    o.set("linearDamping", d.linearDamping);
    o.set("angularDamping", d.angularDamping);
    o.set("gravityScale", d.gravityScale);
    o.set("sleepThreshold", d.sleepThreshold);
    o.set("name", d.name ? std::string(d.name) : std::string());
    o.set("motionLocks", d.motionLocks);
    o.set("enableSleep", d.enableSleep);
    o.set("isAwake", d.isAwake);
    o.set("isBullet", d.isBullet);
    o.set("isEnabled", d.isEnabled);
    o.set("allowFastRotation", d.allowFastRotation);
    return o;
}

void b2BodyDefApply(b2BodyDef& d, val o) {
    if (!o["type"].isUndefined()) d.type = o["type"].as<b2BodyType>();
    if (!o["position"].isUndefined()) d.position = o["position"].as<b2Vec2>();
    if (!o["rotation"].isUndefined()) d.rotation = o["rotation"].as<b2Rot>();
    if (!o["linearVelocity"].isUndefined()) d.linearVelocity = o["linearVelocity"].as<b2Vec2>();
    if (!o["angularVelocity"].isUndefined()) d.angularVelocity = o["angularVelocity"].as<float>();
    if (!o["linearDamping"].isUndefined()) d.linearDamping = o["linearDamping"].as<float>();
    if (!o["angularDamping"].isUndefined()) d.angularDamping = o["angularDamping"].as<float>();
    if (!o["gravityScale"].isUndefined()) d.gravityScale = o["gravityScale"].as<float>();
    if (!o["sleepThreshold"].isUndefined()) d.sleepThreshold = o["sleepThreshold"].as<float>();
    if (!o["name"].isUndefined()) { static std::string s; s = o["name"].as<std::string>(); d.name = s.c_str(); }
    if (!o["motionLocks"].isUndefined()) d.motionLocks = o["motionLocks"].as<b2MotionLocks>();
    if (!o["enableSleep"].isUndefined()) d.enableSleep = o["enableSleep"].as<bool>();
    if (!o["isAwake"].isUndefined()) d.isAwake = o["isAwake"].as<bool>();
    if (!o["isBullet"].isUndefined()) d.isBullet = o["isBullet"].as<bool>();
    if (!o["isEnabled"].isUndefined()) d.isEnabled = o["isEnabled"].as<bool>();
    if (!o["allowFastRotation"].isUndefined()) d.allowFastRotation = o["allowFastRotation"].as<bool>();
}

b2BodyDef b2BodyDefFromJS(val o) {
    b2BodyDef d = b2DefaultBodyDef();
    b2BodyDefApply(d, o);
    return d;
}

val b2FilterToJS(const b2Filter& d) {
    val o = val::object();
    o.set("categoryBits", static_cast<double>(d.categoryBits));
    o.set("maskBits", static_cast<double>(d.maskBits));
    o.set("groupIndex", d.groupIndex);
    return o;
}

void b2FilterApply(b2Filter& d, val o) {
    if (!o["categoryBits"].isUndefined()) d.categoryBits = toU64(o["categoryBits"].as<double>());
    if (!o["maskBits"].isUndefined()) d.maskBits = toU64(o["maskBits"].as<double>());
    if (!o["groupIndex"].isUndefined()) d.groupIndex = o["groupIndex"].as<int>();
}

b2Filter b2FilterFromJS(val o) {
    b2Filter d = b2DefaultFilter();
    b2FilterApply(d, o);
    return d;
}

val b2QueryFilterToJS(const b2QueryFilter& d) {
    val o = val::object();
    o.set("categoryBits", static_cast<double>(d.categoryBits));
    o.set("maskBits", static_cast<double>(d.maskBits));
    return o;
}

void b2QueryFilterApply(b2QueryFilter& d, val o) {
    if (!o["categoryBits"].isUndefined()) d.categoryBits = toU64(o["categoryBits"].as<double>());
    if (!o["maskBits"].isUndefined()) d.maskBits = toU64(o["maskBits"].as<double>());
}

b2QueryFilter b2QueryFilterFromJS(val o) {
    b2QueryFilter d = b2DefaultQueryFilter();
    b2QueryFilterApply(d, o);
    return d;
}

val b2SurfaceMaterialToJS(const b2SurfaceMaterial& d) {
    val o = val::object();
    o.set("friction", d.friction);
    o.set("restitution", d.restitution);
    o.set("rollingResistance", d.rollingResistance);
    o.set("tangentSpeed", d.tangentSpeed);
    o.set("userMaterialId", static_cast<double>(d.userMaterialId));
    o.set("customColor", d.customColor);
    return o;
}

void b2SurfaceMaterialApply(b2SurfaceMaterial& d, val o) {
    if (!o["friction"].isUndefined()) d.friction = o["friction"].as<float>();
    if (!o["restitution"].isUndefined()) d.restitution = o["restitution"].as<float>();
    if (!o["rollingResistance"].isUndefined()) d.rollingResistance = o["rollingResistance"].as<float>();
    if (!o["tangentSpeed"].isUndefined()) d.tangentSpeed = o["tangentSpeed"].as<float>();
    if (!o["userMaterialId"].isUndefined()) d.userMaterialId = toU64(o["userMaterialId"].as<double>());
    if (!o["customColor"].isUndefined()) d.customColor = o["customColor"].as<uint32_t>();
}

b2SurfaceMaterial b2SurfaceMaterialFromJS(val o) {
    b2SurfaceMaterial d = b2DefaultSurfaceMaterial();
    b2SurfaceMaterialApply(d, o);
    return d;
}

val b2ShapeDefToJS(const b2ShapeDef& d) {
    val o = val::object();
    o.set("material", b2SurfaceMaterialToJS(d.material));
    o.set("density", d.density);
    o.set("filter", b2FilterToJS(d.filter));
    o.set("enableCustomFiltering", d.enableCustomFiltering);
    o.set("isSensor", d.isSensor);
    o.set("enableSensorEvents", d.enableSensorEvents);
    o.set("enableContactEvents", d.enableContactEvents);
    o.set("enableHitEvents", d.enableHitEvents);
    o.set("enablePreSolveEvents", d.enablePreSolveEvents);
    o.set("invokeContactCreation", d.invokeContactCreation);
    o.set("updateBodyMass", d.updateBodyMass);
    return o;
}

void b2ShapeDefApply(b2ShapeDef& d, val o) {
    if (!o["material"].isUndefined()) b2SurfaceMaterialApply(d.material, o["material"]);
    if (!o["density"].isUndefined()) d.density = o["density"].as<float>();
    if (!o["filter"].isUndefined()) b2FilterApply(d.filter, o["filter"]);
    if (!o["enableCustomFiltering"].isUndefined()) d.enableCustomFiltering = o["enableCustomFiltering"].as<bool>();
    if (!o["isSensor"].isUndefined()) d.isSensor = o["isSensor"].as<bool>();
    if (!o["enableSensorEvents"].isUndefined()) d.enableSensorEvents = o["enableSensorEvents"].as<bool>();
    if (!o["enableContactEvents"].isUndefined()) d.enableContactEvents = o["enableContactEvents"].as<bool>();
    if (!o["enableHitEvents"].isUndefined()) d.enableHitEvents = o["enableHitEvents"].as<bool>();
    if (!o["enablePreSolveEvents"].isUndefined()) d.enablePreSolveEvents = o["enablePreSolveEvents"].as<bool>();
    if (!o["invokeContactCreation"].isUndefined()) d.invokeContactCreation = o["invokeContactCreation"].as<bool>();
    if (!o["updateBodyMass"].isUndefined()) d.updateBodyMass = o["updateBodyMass"].as<bool>();
}

b2ShapeDef b2ShapeDefFromJS(val o) {
    b2ShapeDef d = b2DefaultShapeDef();
    b2ShapeDefApply(d, o);
    return d;
}

val b2ChainDefToJS(const b2ChainDef& d) {
    val o = val::object();
    o.set("filter", b2FilterToJS(d.filter));
    o.set("isLoop", d.isLoop);
    o.set("enableSensorEvents", d.enableSensorEvents);
    o.set("points", arrayToVal(d.points, d.count));
    { val a = val::array(); for (int i = 0; i < d.materialCount; i++) a.set(i, b2SurfaceMaterialToJS(d.materials[i])); o.set("materials", a); }
    return o;
}

void b2ChainDefApply(b2ChainDef& d, val o) {
    if (!o["filter"].isUndefined()) b2FilterApply(d.filter, o["filter"]);
    if (!o["isLoop"].isUndefined()) d.isLoop = o["isLoop"].as<bool>();
    if (!o["enableSensorEvents"].isUndefined()) d.enableSensorEvents = o["enableSensorEvents"].as<bool>();
}

b2ChainDef b2ChainDefFromJS(val o) {
    b2ChainDef d = b2DefaultChainDef();
    b2ChainDefApply(d, o);
    return d;
}

val b2DistanceJointDefToJS(const b2DistanceJointDef& d) {
    val o = val::object();
    o.set("base", b2JointDefToJS(d.base));
    o.set("length", d.length);
    o.set("enableSpring", d.enableSpring);
    o.set("lowerSpringForce", d.lowerSpringForce);
    o.set("upperSpringForce", d.upperSpringForce);
    o.set("hertz", d.hertz);
    o.set("dampingRatio", d.dampingRatio);
    o.set("enableLimit", d.enableLimit);
    o.set("minLength", d.minLength);
    o.set("maxLength", d.maxLength);
    o.set("enableMotor", d.enableMotor);
    o.set("maxMotorForce", d.maxMotorForce);
    o.set("motorSpeed", d.motorSpeed);
    return o;
}

void b2DistanceJointDefApply(b2DistanceJointDef& d, val o) {
    if (!o["base"].isUndefined()) b2JointDefApply(d.base, o["base"]);
    if (!o["length"].isUndefined()) d.length = o["length"].as<float>();
    if (!o["enableSpring"].isUndefined()) d.enableSpring = o["enableSpring"].as<bool>();
    if (!o["lowerSpringForce"].isUndefined()) d.lowerSpringForce = o["lowerSpringForce"].as<float>();
    if (!o["upperSpringForce"].isUndefined()) d.upperSpringForce = o["upperSpringForce"].as<float>();
    if (!o["hertz"].isUndefined()) d.hertz = o["hertz"].as<float>();
    if (!o["dampingRatio"].isUndefined()) d.dampingRatio = o["dampingRatio"].as<float>();
    if (!o["enableLimit"].isUndefined()) d.enableLimit = o["enableLimit"].as<bool>();
    if (!o["minLength"].isUndefined()) d.minLength = o["minLength"].as<float>();
    if (!o["maxLength"].isUndefined()) d.maxLength = o["maxLength"].as<float>();
    if (!o["enableMotor"].isUndefined()) d.enableMotor = o["enableMotor"].as<bool>();
    if (!o["maxMotorForce"].isUndefined()) d.maxMotorForce = o["maxMotorForce"].as<float>();
    if (!o["motorSpeed"].isUndefined()) d.motorSpeed = o["motorSpeed"].as<float>();
}

b2DistanceJointDef b2DistanceJointDefFromJS(val o) {
    b2DistanceJointDef d = b2DefaultDistanceJointDef();
    b2DistanceJointDefApply(d, o);
    return d;
}

val b2MotorJointDefToJS(const b2MotorJointDef& d) {
    val o = val::object();
    o.set("base", b2JointDefToJS(d.base));
    o.set("linearVelocity", d.linearVelocity);
    o.set("maxVelocityForce", d.maxVelocityForce);
    o.set("angularVelocity", d.angularVelocity);
    o.set("maxVelocityTorque", d.maxVelocityTorque);
    o.set("linearHertz", d.linearHertz);
    o.set("linearDampingRatio", d.linearDampingRatio);
    o.set("maxSpringForce", d.maxSpringForce);
    o.set("angularHertz", d.angularHertz);
    o.set("angularDampingRatio", d.angularDampingRatio);
    o.set("maxSpringTorque", d.maxSpringTorque);
    return o;
}

void b2MotorJointDefApply(b2MotorJointDef& d, val o) {
    if (!o["base"].isUndefined()) b2JointDefApply(d.base, o["base"]);
    if (!o["linearVelocity"].isUndefined()) d.linearVelocity = o["linearVelocity"].as<b2Vec2>();
    if (!o["maxVelocityForce"].isUndefined()) d.maxVelocityForce = o["maxVelocityForce"].as<float>();
    if (!o["angularVelocity"].isUndefined()) d.angularVelocity = o["angularVelocity"].as<float>();
    if (!o["maxVelocityTorque"].isUndefined()) d.maxVelocityTorque = o["maxVelocityTorque"].as<float>();
    if (!o["linearHertz"].isUndefined()) d.linearHertz = o["linearHertz"].as<float>();
    if (!o["linearDampingRatio"].isUndefined()) d.linearDampingRatio = o["linearDampingRatio"].as<float>();
    if (!o["maxSpringForce"].isUndefined()) d.maxSpringForce = o["maxSpringForce"].as<float>();
    if (!o["angularHertz"].isUndefined()) d.angularHertz = o["angularHertz"].as<float>();
    if (!o["angularDampingRatio"].isUndefined()) d.angularDampingRatio = o["angularDampingRatio"].as<float>();
    if (!o["maxSpringTorque"].isUndefined()) d.maxSpringTorque = o["maxSpringTorque"].as<float>();
}

b2MotorJointDef b2MotorJointDefFromJS(val o) {
    b2MotorJointDef d = b2DefaultMotorJointDef();
    b2MotorJointDefApply(d, o);
    return d;
}

val b2FilterJointDefToJS(const b2FilterJointDef& d) {
    val o = val::object();
    o.set("base", b2JointDefToJS(d.base));
    return o;
}

void b2FilterJointDefApply(b2FilterJointDef& d, val o) {
    if (!o["base"].isUndefined()) b2JointDefApply(d.base, o["base"]);
}

b2FilterJointDef b2FilterJointDefFromJS(val o) {
    b2FilterJointDef d = b2DefaultFilterJointDef();
    b2FilterJointDefApply(d, o);
    return d;
}

val b2PrismaticJointDefToJS(const b2PrismaticJointDef& d) {
    val o = val::object();
    o.set("base", b2JointDefToJS(d.base));
    o.set("enableSpring", d.enableSpring);
    o.set("hertz", d.hertz);
    o.set("dampingRatio", d.dampingRatio);
    o.set("targetTranslation", d.targetTranslation);
    o.set("enableLimit", d.enableLimit);
    o.set("lowerTranslation", d.lowerTranslation);
    o.set("upperTranslation", d.upperTranslation);
    o.set("enableMotor", d.enableMotor);
    o.set("maxMotorForce", d.maxMotorForce);
    o.set("motorSpeed", d.motorSpeed);
    return o;
}

void b2PrismaticJointDefApply(b2PrismaticJointDef& d, val o) {
    if (!o["base"].isUndefined()) b2JointDefApply(d.base, o["base"]);
    if (!o["enableSpring"].isUndefined()) d.enableSpring = o["enableSpring"].as<bool>();
    if (!o["hertz"].isUndefined()) d.hertz = o["hertz"].as<float>();
    if (!o["dampingRatio"].isUndefined()) d.dampingRatio = o["dampingRatio"].as<float>();
    if (!o["targetTranslation"].isUndefined()) d.targetTranslation = o["targetTranslation"].as<float>();
    if (!o["enableLimit"].isUndefined()) d.enableLimit = o["enableLimit"].as<bool>();
    if (!o["lowerTranslation"].isUndefined()) d.lowerTranslation = o["lowerTranslation"].as<float>();
    if (!o["upperTranslation"].isUndefined()) d.upperTranslation = o["upperTranslation"].as<float>();
    if (!o["enableMotor"].isUndefined()) d.enableMotor = o["enableMotor"].as<bool>();
    if (!o["maxMotorForce"].isUndefined()) d.maxMotorForce = o["maxMotorForce"].as<float>();
    if (!o["motorSpeed"].isUndefined()) d.motorSpeed = o["motorSpeed"].as<float>();
}

b2PrismaticJointDef b2PrismaticJointDefFromJS(val o) {
    b2PrismaticJointDef d = b2DefaultPrismaticJointDef();
    b2PrismaticJointDefApply(d, o);
    return d;
}

val b2RevoluteJointDefToJS(const b2RevoluteJointDef& d) {
    val o = val::object();
    o.set("base", b2JointDefToJS(d.base));
    o.set("targetAngle", d.targetAngle);
    o.set("enableSpring", d.enableSpring);
    o.set("hertz", d.hertz);
    o.set("dampingRatio", d.dampingRatio);
    o.set("enableLimit", d.enableLimit);
    o.set("lowerAngle", d.lowerAngle);
    o.set("upperAngle", d.upperAngle);
    o.set("enableMotor", d.enableMotor);
    o.set("maxMotorTorque", d.maxMotorTorque);
    o.set("motorSpeed", d.motorSpeed);
    return o;
}

void b2RevoluteJointDefApply(b2RevoluteJointDef& d, val o) {
    if (!o["base"].isUndefined()) b2JointDefApply(d.base, o["base"]);
    if (!o["targetAngle"].isUndefined()) d.targetAngle = o["targetAngle"].as<float>();
    if (!o["enableSpring"].isUndefined()) d.enableSpring = o["enableSpring"].as<bool>();
    if (!o["hertz"].isUndefined()) d.hertz = o["hertz"].as<float>();
    if (!o["dampingRatio"].isUndefined()) d.dampingRatio = o["dampingRatio"].as<float>();
    if (!o["enableLimit"].isUndefined()) d.enableLimit = o["enableLimit"].as<bool>();
    if (!o["lowerAngle"].isUndefined()) d.lowerAngle = o["lowerAngle"].as<float>();
    if (!o["upperAngle"].isUndefined()) d.upperAngle = o["upperAngle"].as<float>();
    if (!o["enableMotor"].isUndefined()) d.enableMotor = o["enableMotor"].as<bool>();
    if (!o["maxMotorTorque"].isUndefined()) d.maxMotorTorque = o["maxMotorTorque"].as<float>();
    if (!o["motorSpeed"].isUndefined()) d.motorSpeed = o["motorSpeed"].as<float>();
}

b2RevoluteJointDef b2RevoluteJointDefFromJS(val o) {
    b2RevoluteJointDef d = b2DefaultRevoluteJointDef();
    b2RevoluteJointDefApply(d, o);
    return d;
}

val b2WeldJointDefToJS(const b2WeldJointDef& d) {
    val o = val::object();
    o.set("base", b2JointDefToJS(d.base));
    o.set("linearHertz", d.linearHertz);
    o.set("angularHertz", d.angularHertz);
    o.set("linearDampingRatio", d.linearDampingRatio);
    o.set("angularDampingRatio", d.angularDampingRatio);
    return o;
}

void b2WeldJointDefApply(b2WeldJointDef& d, val o) {
    if (!o["base"].isUndefined()) b2JointDefApply(d.base, o["base"]);
    if (!o["linearHertz"].isUndefined()) d.linearHertz = o["linearHertz"].as<float>();
    if (!o["angularHertz"].isUndefined()) d.angularHertz = o["angularHertz"].as<float>();
    if (!o["linearDampingRatio"].isUndefined()) d.linearDampingRatio = o["linearDampingRatio"].as<float>();
    if (!o["angularDampingRatio"].isUndefined()) d.angularDampingRatio = o["angularDampingRatio"].as<float>();
}

b2WeldJointDef b2WeldJointDefFromJS(val o) {
    b2WeldJointDef d = b2DefaultWeldJointDef();
    b2WeldJointDefApply(d, o);
    return d;
}

val b2WheelJointDefToJS(const b2WheelJointDef& d) {
    val o = val::object();
    o.set("base", b2JointDefToJS(d.base));
    o.set("enableSpring", d.enableSpring);
    o.set("hertz", d.hertz);
    o.set("dampingRatio", d.dampingRatio);
    o.set("enableLimit", d.enableLimit);
    o.set("lowerTranslation", d.lowerTranslation);
    o.set("upperTranslation", d.upperTranslation);
    o.set("enableMotor", d.enableMotor);
    o.set("maxMotorTorque", d.maxMotorTorque);
    o.set("motorSpeed", d.motorSpeed);
    return o;
}

void b2WheelJointDefApply(b2WheelJointDef& d, val o) {
    if (!o["base"].isUndefined()) b2JointDefApply(d.base, o["base"]);
    if (!o["enableSpring"].isUndefined()) d.enableSpring = o["enableSpring"].as<bool>();
    if (!o["hertz"].isUndefined()) d.hertz = o["hertz"].as<float>();
    if (!o["dampingRatio"].isUndefined()) d.dampingRatio = o["dampingRatio"].as<float>();
    if (!o["enableLimit"].isUndefined()) d.enableLimit = o["enableLimit"].as<bool>();
    if (!o["lowerTranslation"].isUndefined()) d.lowerTranslation = o["lowerTranslation"].as<float>();
    if (!o["upperTranslation"].isUndefined()) d.upperTranslation = o["upperTranslation"].as<float>();
    if (!o["enableMotor"].isUndefined()) d.enableMotor = o["enableMotor"].as<bool>();
    if (!o["maxMotorTorque"].isUndefined()) d.maxMotorTorque = o["maxMotorTorque"].as<float>();
    if (!o["motorSpeed"].isUndefined()) d.motorSpeed = o["motorSpeed"].as<float>();
}

b2WheelJointDef b2WheelJointDefFromJS(val o) {
    b2WheelJointDef d = b2DefaultWheelJointDef();
    b2WheelJointDefApply(d, o);
    return d;
}

val b2ExplosionDefToJS(const b2ExplosionDef& d) {
    val o = val::object();
    o.set("maskBits", static_cast<double>(d.maskBits));
    o.set("position", d.position);
    o.set("radius", d.radius);
    o.set("falloff", d.falloff);
    o.set("impulsePerLength", d.impulsePerLength);
    return o;
}

void b2ExplosionDefApply(b2ExplosionDef& d, val o) {
    if (!o["maskBits"].isUndefined()) d.maskBits = toU64(o["maskBits"].as<double>());
    if (!o["position"].isUndefined()) d.position = o["position"].as<b2Vec2>();
    if (!o["radius"].isUndefined()) d.radius = o["radius"].as<float>();
    if (!o["falloff"].isUndefined()) d.falloff = o["falloff"].as<float>();
    if (!o["impulsePerLength"].isUndefined()) d.impulsePerLength = o["impulsePerLength"].as<float>();
}

b2ExplosionDef b2ExplosionDefFromJS(val o) {
    b2ExplosionDef d = b2DefaultExplosionDef();
    b2ExplosionDefApply(d, o);
    return d;
}

val b2DebugDrawToJS(const b2DebugDraw& d) {
    val o = val::object();
    o.set("drawingBounds", d.drawingBounds);
    o.set("forceScale", d.forceScale);
    o.set("jointScale", d.jointScale);
    o.set("drawShapes", d.drawShapes);
    o.set("drawJoints", d.drawJoints);
    o.set("drawJointExtras", d.drawJointExtras);
    o.set("drawBounds", d.drawBounds);
    o.set("drawMass", d.drawMass);
    o.set("drawBodyNames", d.drawBodyNames);
    o.set("drawContactPoints", d.drawContactPoints);
    o.set("drawGraphColors", d.drawGraphColors);
    o.set("drawContactFeatures", d.drawContactFeatures);
    o.set("drawContactNormals", d.drawContactNormals);
    o.set("drawContactForces", d.drawContactForces);
    o.set("drawFrictionForces", d.drawFrictionForces);
    o.set("drawIslands", d.drawIslands);
    return o;
}

void b2DebugDrawApply(b2DebugDraw& d, val o) {
    if (!o["drawingBounds"].isUndefined()) d.drawingBounds = o["drawingBounds"].as<b2AABB>();
    if (!o["forceScale"].isUndefined()) d.forceScale = o["forceScale"].as<float>();
    if (!o["jointScale"].isUndefined()) d.jointScale = o["jointScale"].as<float>();
    if (!o["drawShapes"].isUndefined()) d.drawShapes = o["drawShapes"].as<bool>();
    if (!o["drawJoints"].isUndefined()) d.drawJoints = o["drawJoints"].as<bool>();
    if (!o["drawJointExtras"].isUndefined()) d.drawJointExtras = o["drawJointExtras"].as<bool>();
    if (!o["drawBounds"].isUndefined()) d.drawBounds = o["drawBounds"].as<bool>();
    if (!o["drawMass"].isUndefined()) d.drawMass = o["drawMass"].as<bool>();
    if (!o["drawBodyNames"].isUndefined()) d.drawBodyNames = o["drawBodyNames"].as<bool>();
    if (!o["drawContactPoints"].isUndefined()) d.drawContactPoints = o["drawContactPoints"].as<bool>();
    if (!o["drawGraphColors"].isUndefined()) d.drawGraphColors = o["drawGraphColors"].as<bool>();
    if (!o["drawContactFeatures"].isUndefined()) d.drawContactFeatures = o["drawContactFeatures"].as<bool>();
    if (!o["drawContactNormals"].isUndefined()) d.drawContactNormals = o["drawContactNormals"].as<bool>();
    if (!o["drawContactForces"].isUndefined()) d.drawContactForces = o["drawContactForces"].as<bool>();
    if (!o["drawFrictionForces"].isUndefined()) d.drawFrictionForces = o["drawFrictionForces"].as<bool>();
    if (!o["drawIslands"].isUndefined()) d.drawIslands = o["drawIslands"].as<bool>();
}

b2DebugDraw b2DebugDrawFromJS(val o) {
    b2DebugDraw d = b2DefaultDebugDraw();
    b2DebugDrawApply(d, o);
    return d;
}

EMSCRIPTEN_BINDINGS(box2d_generated) {
    // ---- enums ----
    enum_<b2TOIState>("b2TOIState")
        .value("b2_toiStateUnknown", b2_toiStateUnknown)
        .value("b2_toiStateFailed", b2_toiStateFailed)
        .value("b2_toiStateOverlapped", b2_toiStateOverlapped)
        .value("b2_toiStateHit", b2_toiStateHit)
        .value("b2_toiStateSeparated", b2_toiStateSeparated);
    enum_<b2BodyType>("b2BodyType")
        .value("b2_staticBody", b2_staticBody)
        .value("b2_kinematicBody", b2_kinematicBody)
        .value("b2_dynamicBody", b2_dynamicBody)
        .value("b2_bodyTypeCount", b2_bodyTypeCount);
    enum_<b2ShapeType>("b2ShapeType")
        .value("b2_circleShape", b2_circleShape)
        .value("b2_capsuleShape", b2_capsuleShape)
        .value("b2_segmentShape", b2_segmentShape)
        .value("b2_polygonShape", b2_polygonShape)
        .value("b2_chainSegmentShape", b2_chainSegmentShape)
        .value("b2_shapeTypeCount", b2_shapeTypeCount);
    enum_<b2JointType>("b2JointType")
        .value("b2_distanceJoint", b2_distanceJoint)
        .value("b2_filterJoint", b2_filterJoint)
        .value("b2_motorJoint", b2_motorJoint)
        .value("b2_prismaticJoint", b2_prismaticJoint)
        .value("b2_revoluteJoint", b2_revoluteJoint)
        .value("b2_weldJoint", b2_weldJoint)
        .value("b2_wheelJoint", b2_wheelJoint);
    enum_<b2HexColor>("b2HexColor")
        .value("b2_colorAliceBlue", b2_colorAliceBlue)
        .value("b2_colorAntiqueWhite", b2_colorAntiqueWhite)
        .value("b2_colorAqua", b2_colorAqua)
        .value("b2_colorAquamarine", b2_colorAquamarine)
        .value("b2_colorAzure", b2_colorAzure)
        .value("b2_colorBeige", b2_colorBeige)
        .value("b2_colorBisque", b2_colorBisque)
        .value("b2_colorBlack", b2_colorBlack)
        .value("b2_colorBlanchedAlmond", b2_colorBlanchedAlmond)
        .value("b2_colorBlue", b2_colorBlue)
        .value("b2_colorBlueViolet", b2_colorBlueViolet)
        .value("b2_colorBrown", b2_colorBrown)
        .value("b2_colorBurlywood", b2_colorBurlywood)
        .value("b2_colorCadetBlue", b2_colorCadetBlue)
        .value("b2_colorChartreuse", b2_colorChartreuse)
        .value("b2_colorChocolate", b2_colorChocolate)
        .value("b2_colorCoral", b2_colorCoral)
        .value("b2_colorCornflowerBlue", b2_colorCornflowerBlue)
        .value("b2_colorCornsilk", b2_colorCornsilk)
        .value("b2_colorCrimson", b2_colorCrimson)
        .value("b2_colorCyan", b2_colorCyan)
        .value("b2_colorDarkBlue", b2_colorDarkBlue)
        .value("b2_colorDarkCyan", b2_colorDarkCyan)
        .value("b2_colorDarkGoldenRod", b2_colorDarkGoldenRod)
        .value("b2_colorDarkGray", b2_colorDarkGray)
        .value("b2_colorDarkGreen", b2_colorDarkGreen)
        .value("b2_colorDarkKhaki", b2_colorDarkKhaki)
        .value("b2_colorDarkMagenta", b2_colorDarkMagenta)
        .value("b2_colorDarkOliveGreen", b2_colorDarkOliveGreen)
        .value("b2_colorDarkOrange", b2_colorDarkOrange)
        .value("b2_colorDarkOrchid", b2_colorDarkOrchid)
        .value("b2_colorDarkRed", b2_colorDarkRed)
        .value("b2_colorDarkSalmon", b2_colorDarkSalmon)
        .value("b2_colorDarkSeaGreen", b2_colorDarkSeaGreen)
        .value("b2_colorDarkSlateBlue", b2_colorDarkSlateBlue)
        .value("b2_colorDarkSlateGray", b2_colorDarkSlateGray)
        .value("b2_colorDarkTurquoise", b2_colorDarkTurquoise)
        .value("b2_colorDarkViolet", b2_colorDarkViolet)
        .value("b2_colorDeepPink", b2_colorDeepPink)
        .value("b2_colorDeepSkyBlue", b2_colorDeepSkyBlue)
        .value("b2_colorDimGray", b2_colorDimGray)
        .value("b2_colorDodgerBlue", b2_colorDodgerBlue)
        .value("b2_colorFireBrick", b2_colorFireBrick)
        .value("b2_colorFloralWhite", b2_colorFloralWhite)
        .value("b2_colorForestGreen", b2_colorForestGreen)
        .value("b2_colorFuchsia", b2_colorFuchsia)
        .value("b2_colorGainsboro", b2_colorGainsboro)
        .value("b2_colorGhostWhite", b2_colorGhostWhite)
        .value("b2_colorGold", b2_colorGold)
        .value("b2_colorGoldenRod", b2_colorGoldenRod)
        .value("b2_colorGray", b2_colorGray)
        .value("b2_colorGreen", b2_colorGreen)
        .value("b2_colorGreenYellow", b2_colorGreenYellow)
        .value("b2_colorHoneyDew", b2_colorHoneyDew)
        .value("b2_colorHotPink", b2_colorHotPink)
        .value("b2_colorIndianRed", b2_colorIndianRed)
        .value("b2_colorIndigo", b2_colorIndigo)
        .value("b2_colorIvory", b2_colorIvory)
        .value("b2_colorKhaki", b2_colorKhaki)
        .value("b2_colorLavender", b2_colorLavender)
        .value("b2_colorLavenderBlush", b2_colorLavenderBlush)
        .value("b2_colorLawnGreen", b2_colorLawnGreen)
        .value("b2_colorLemonChiffon", b2_colorLemonChiffon)
        .value("b2_colorLightBlue", b2_colorLightBlue)
        .value("b2_colorLightCoral", b2_colorLightCoral)
        .value("b2_colorLightCyan", b2_colorLightCyan)
        .value("b2_colorLightGoldenRodYellow", b2_colorLightGoldenRodYellow)
        .value("b2_colorLightGray", b2_colorLightGray)
        .value("b2_colorLightGreen", b2_colorLightGreen)
        .value("b2_colorLightPink", b2_colorLightPink)
        .value("b2_colorLightSalmon", b2_colorLightSalmon)
        .value("b2_colorLightSeaGreen", b2_colorLightSeaGreen)
        .value("b2_colorLightSkyBlue", b2_colorLightSkyBlue)
        .value("b2_colorLightSlateGray", b2_colorLightSlateGray)
        .value("b2_colorLightSteelBlue", b2_colorLightSteelBlue)
        .value("b2_colorLightYellow", b2_colorLightYellow)
        .value("b2_colorLime", b2_colorLime)
        .value("b2_colorLimeGreen", b2_colorLimeGreen)
        .value("b2_colorLinen", b2_colorLinen)
        .value("b2_colorMagenta", b2_colorMagenta)
        .value("b2_colorMaroon", b2_colorMaroon)
        .value("b2_colorMediumAquaMarine", b2_colorMediumAquaMarine)
        .value("b2_colorMediumBlue", b2_colorMediumBlue)
        .value("b2_colorMediumOrchid", b2_colorMediumOrchid)
        .value("b2_colorMediumPurple", b2_colorMediumPurple)
        .value("b2_colorMediumSeaGreen", b2_colorMediumSeaGreen)
        .value("b2_colorMediumSlateBlue", b2_colorMediumSlateBlue)
        .value("b2_colorMediumSpringGreen", b2_colorMediumSpringGreen)
        .value("b2_colorMediumTurquoise", b2_colorMediumTurquoise)
        .value("b2_colorMediumVioletRed", b2_colorMediumVioletRed)
        .value("b2_colorMidnightBlue", b2_colorMidnightBlue)
        .value("b2_colorMintCream", b2_colorMintCream)
        .value("b2_colorMistyRose", b2_colorMistyRose)
        .value("b2_colorMoccasin", b2_colorMoccasin)
        .value("b2_colorNavajoWhite", b2_colorNavajoWhite)
        .value("b2_colorNavy", b2_colorNavy)
        .value("b2_colorOldLace", b2_colorOldLace)
        .value("b2_colorOlive", b2_colorOlive)
        .value("b2_colorOliveDrab", b2_colorOliveDrab)
        .value("b2_colorOrange", b2_colorOrange)
        .value("b2_colorOrangeRed", b2_colorOrangeRed)
        .value("b2_colorOrchid", b2_colorOrchid)
        .value("b2_colorPaleGoldenRod", b2_colorPaleGoldenRod)
        .value("b2_colorPaleGreen", b2_colorPaleGreen)
        .value("b2_colorPaleTurquoise", b2_colorPaleTurquoise)
        .value("b2_colorPaleVioletRed", b2_colorPaleVioletRed)
        .value("b2_colorPapayaWhip", b2_colorPapayaWhip)
        .value("b2_colorPeachPuff", b2_colorPeachPuff)
        .value("b2_colorPeru", b2_colorPeru)
        .value("b2_colorPink", b2_colorPink)
        .value("b2_colorPlum", b2_colorPlum)
        .value("b2_colorPowderBlue", b2_colorPowderBlue)
        .value("b2_colorPurple", b2_colorPurple)
        .value("b2_colorRebeccaPurple", b2_colorRebeccaPurple)
        .value("b2_colorRed", b2_colorRed)
        .value("b2_colorRosyBrown", b2_colorRosyBrown)
        .value("b2_colorRoyalBlue", b2_colorRoyalBlue)
        .value("b2_colorSaddleBrown", b2_colorSaddleBrown)
        .value("b2_colorSalmon", b2_colorSalmon)
        .value("b2_colorSandyBrown", b2_colorSandyBrown)
        .value("b2_colorSeaGreen", b2_colorSeaGreen)
        .value("b2_colorSeaShell", b2_colorSeaShell)
        .value("b2_colorSienna", b2_colorSienna)
        .value("b2_colorSilver", b2_colorSilver)
        .value("b2_colorSkyBlue", b2_colorSkyBlue)
        .value("b2_colorSlateBlue", b2_colorSlateBlue)
        .value("b2_colorSlateGray", b2_colorSlateGray)
        .value("b2_colorSnow", b2_colorSnow)
        .value("b2_colorSpringGreen", b2_colorSpringGreen)
        .value("b2_colorSteelBlue", b2_colorSteelBlue)
        .value("b2_colorTan", b2_colorTan)
        .value("b2_colorTeal", b2_colorTeal)
        .value("b2_colorThistle", b2_colorThistle)
        .value("b2_colorTomato", b2_colorTomato)
        .value("b2_colorTurquoise", b2_colorTurquoise)
        .value("b2_colorViolet", b2_colorViolet)
        .value("b2_colorWheat", b2_colorWheat)
        .value("b2_colorWhite", b2_colorWhite)
        .value("b2_colorWhiteSmoke", b2_colorWhiteSmoke)
        .value("b2_colorYellow", b2_colorYellow)
        .value("b2_colorYellowGreen", b2_colorYellowGreen)
        .value("b2_colorBox2DRed", b2_colorBox2DRed)
        .value("b2_colorBox2DBlue", b2_colorBox2DBlue)
        .value("b2_colorBox2DGreen", b2_colorBox2DGreen)
        .value("b2_colorBox2DYellow", b2_colorBox2DYellow);

    // ---- value objects ----
    value_object<b2Version>("b2Version")
        .field("major", &b2Version::major)
        .field("minor", &b2Version::minor)
        .field("revision", &b2Version::revision);
    value_object<b2Vec2>("b2Vec2")
        .field("x", &b2Vec2::x)
        .field("y", &b2Vec2::y);
    value_object<b2CosSin>("b2CosSin")
        .field("cosine", &b2CosSin::cosine)
        .field("sine", &b2CosSin::sine);
    value_object<b2Rot>("b2Rot")
        .field("c", &b2Rot::c)
        .field("s", &b2Rot::s);
    value_object<b2Transform>("b2Transform")
        .field("p", &b2Transform::p)
        .field("q", &b2Transform::q);
    value_object<b2Mat22>("b2Mat22")
        .field("cx", &b2Mat22::cx)
        .field("cy", &b2Mat22::cy);
    value_object<b2AABB>("b2AABB")
        .field("lowerBound", &b2AABB::lowerBound)
        .field("upperBound", &b2AABB::upperBound);
    value_object<b2Plane>("b2Plane")
        .field("normal", &b2Plane::normal)
        .field("offset", &b2Plane::offset);
    value_object<b2RayCastInput>("b2RayCastInput")
        .field("origin", &b2RayCastInput::origin)
        .field("translation", &b2RayCastInput::translation)
        .field("maxFraction", &b2RayCastInput::maxFraction);
    value_object<b2ShapeProxy>("b2ShapeProxy")
        .field("points", &get_b2ShapeProxy_points, &set_b2ShapeProxy_points)
        .field("count", &get_b2ShapeProxy_count, &set_b2ShapeProxy_count)
        .field("radius", &b2ShapeProxy::radius);
    value_object<b2ShapeCastInput>("b2ShapeCastInput")
        .field("proxy", &b2ShapeCastInput::proxy)
        .field("translation", &b2ShapeCastInput::translation)
        .field("maxFraction", &b2ShapeCastInput::maxFraction)
        .field("canEncroach", &b2ShapeCastInput::canEncroach);
    value_object<b2CastOutput>("b2CastOutput")
        .field("normal", &b2CastOutput::normal)
        .field("point", &b2CastOutput::point)
        .field("fraction", &b2CastOutput::fraction)
        .field("iterations", &b2CastOutput::iterations)
        .field("hit", &b2CastOutput::hit);
    value_object<b2MassData>("b2MassData")
        .field("mass", &b2MassData::mass)
        .field("center", &b2MassData::center)
        .field("rotationalInertia", &b2MassData::rotationalInertia);
    value_object<b2Circle>("b2Circle")
        .field("center", &b2Circle::center)
        .field("radius", &b2Circle::radius);
    value_object<b2Capsule>("b2Capsule")
        .field("center1", &b2Capsule::center1)
        .field("center2", &b2Capsule::center2)
        .field("radius", &b2Capsule::radius);
    value_object<b2Polygon>("b2Polygon")
        .field("vertices", &get_b2Polygon_vertices, &set_b2Polygon_vertices)
        .field("normals", &get_b2Polygon_normals, &set_b2Polygon_normals)
        .field("centroid", &b2Polygon::centroid)
        .field("radius", &b2Polygon::radius)
        .field("count", &get_b2Polygon_count, &set_b2Polygon_count);
    value_object<b2Segment>("b2Segment")
        .field("point1", &b2Segment::point1)
        .field("point2", &b2Segment::point2);
    value_object<b2ChainSegment>("b2ChainSegment")
        .field("ghost1", &b2ChainSegment::ghost1)
        .field("segment", &b2ChainSegment::segment)
        .field("ghost2", &b2ChainSegment::ghost2)
        .field("chainId", &b2ChainSegment::chainId);
    value_object<b2Hull>("b2Hull")
        .field("points", &get_b2Hull_points, &set_b2Hull_points)
        .field("count", &get_b2Hull_count, &set_b2Hull_count);
    value_object<b2SegmentDistanceResult>("b2SegmentDistanceResult")
        .field("closest1", &b2SegmentDistanceResult::closest1)
        .field("closest2", &b2SegmentDistanceResult::closest2)
        .field("fraction1", &b2SegmentDistanceResult::fraction1)
        .field("fraction2", &b2SegmentDistanceResult::fraction2)
        .field("distanceSquared", &b2SegmentDistanceResult::distanceSquared);
    value_object<b2SimplexCache>("b2SimplexCache")
        .field("count", &b2SimplexCache::count)
        .field("indexA", &get_b2SimplexCache_indexA, &set_b2SimplexCache_indexA)
        .field("indexB", &get_b2SimplexCache_indexB, &set_b2SimplexCache_indexB);
    value_object<b2DistanceInput>("b2DistanceInput")
        .field("proxyA", &b2DistanceInput::proxyA)
        .field("proxyB", &b2DistanceInput::proxyB)
        .field("transformA", &b2DistanceInput::transformA)
        .field("transformB", &b2DistanceInput::transformB)
        .field("useRadii", &b2DistanceInput::useRadii);
    value_object<b2DistanceOutput>("b2DistanceOutput")
        .field("pointA", &b2DistanceOutput::pointA)
        .field("pointB", &b2DistanceOutput::pointB)
        .field("normal", &b2DistanceOutput::normal)
        .field("distance", &b2DistanceOutput::distance)
        .field("iterations", &b2DistanceOutput::iterations)
        .field("simplexCount", &b2DistanceOutput::simplexCount);
    value_object<b2SimplexVertex>("b2SimplexVertex")
        .field("wA", &b2SimplexVertex::wA)
        .field("wB", &b2SimplexVertex::wB)
        .field("w", &b2SimplexVertex::w)
        .field("a", &b2SimplexVertex::a)
        .field("indexA", &b2SimplexVertex::indexA)
        .field("indexB", &b2SimplexVertex::indexB);
    value_object<b2Simplex>("b2Simplex")
        .field("v1", &b2Simplex::v1)
        .field("v2", &b2Simplex::v2)
        .field("v3", &b2Simplex::v3)
        .field("count", &b2Simplex::count);
    value_object<b2ShapeCastPairInput>("b2ShapeCastPairInput")
        .field("proxyA", &b2ShapeCastPairInput::proxyA)
        .field("proxyB", &b2ShapeCastPairInput::proxyB)
        .field("transformA", &b2ShapeCastPairInput::transformA)
        .field("transformB", &b2ShapeCastPairInput::transformB)
        .field("translationB", &b2ShapeCastPairInput::translationB)
        .field("maxFraction", &b2ShapeCastPairInput::maxFraction)
        .field("canEncroach", &b2ShapeCastPairInput::canEncroach);
    value_object<b2Sweep>("b2Sweep")
        .field("localCenter", &b2Sweep::localCenter)
        .field("c1", &b2Sweep::c1)
        .field("c2", &b2Sweep::c2)
        .field("q1", &b2Sweep::q1)
        .field("q2", &b2Sweep::q2);
    value_object<b2TOIInput>("b2TOIInput")
        .field("proxyA", &b2TOIInput::proxyA)
        .field("proxyB", &b2TOIInput::proxyB)
        .field("sweepA", &b2TOIInput::sweepA)
        .field("sweepB", &b2TOIInput::sweepB)
        .field("maxFraction", &b2TOIInput::maxFraction);
    value_object<b2TOIOutput>("b2TOIOutput")
        .field("state", &b2TOIOutput::state)
        .field("point", &b2TOIOutput::point)
        .field("normal", &b2TOIOutput::normal)
        .field("fraction", &b2TOIOutput::fraction);
    value_object<b2ManifoldPoint>("b2ManifoldPoint")
        .field("point", &b2ManifoldPoint::point)
        .field("anchorA", &b2ManifoldPoint::anchorA)
        .field("anchorB", &b2ManifoldPoint::anchorB)
        .field("separation", &b2ManifoldPoint::separation)
        .field("normalImpulse", &b2ManifoldPoint::normalImpulse)
        .field("tangentImpulse", &b2ManifoldPoint::tangentImpulse)
        .field("totalNormalImpulse", &b2ManifoldPoint::totalNormalImpulse)
        .field("normalVelocity", &b2ManifoldPoint::normalVelocity)
        .field("id", &b2ManifoldPoint::id)
        .field("persisted", &b2ManifoldPoint::persisted);
    value_object<b2Manifold>("b2Manifold")
        .field("normal", &b2Manifold::normal)
        .field("rollingImpulse", &b2Manifold::rollingImpulse)
        .field("points", &get_b2Manifold_points, &set_b2Manifold_points)
        .field("pointCount", &get_b2Manifold_pointCount, &set_b2Manifold_pointCount);
    value_object<b2TreeStats>("b2TreeStats")
        .field("nodeVisits", &b2TreeStats::nodeVisits)
        .field("leafVisits", &b2TreeStats::leafVisits);
    value_object<b2PlaneResult>("b2PlaneResult")
        .field("plane", &b2PlaneResult::plane)
        .field("point", &b2PlaneResult::point)
        .field("hit", &b2PlaneResult::hit);
    value_object<b2CollisionPlane>("b2CollisionPlane")
        .field("plane", &b2CollisionPlane::plane)
        .field("pushLimit", &b2CollisionPlane::pushLimit)
        .field("push", &b2CollisionPlane::push)
        .field("clipVelocity", &b2CollisionPlane::clipVelocity);
    value_object<b2PlaneSolverResult>("b2PlaneSolverResult")
        .field("translation", &b2PlaneSolverResult::translation)
        .field("iterationCount", &b2PlaneSolverResult::iterationCount);
    value_object<b2WorldId>("b2WorldId")
        .field("index1", &b2WorldId::index1)
        .field("generation", &b2WorldId::generation);
    value_object<b2BodyId>("b2BodyId")
        .field("index1", &b2BodyId::index1)
        .field("world0", &b2BodyId::world0)
        .field("generation", &b2BodyId::generation);
    value_object<b2ShapeId>("b2ShapeId")
        .field("index1", &b2ShapeId::index1)
        .field("world0", &b2ShapeId::world0)
        .field("generation", &b2ShapeId::generation);
    value_object<b2ChainId>("b2ChainId")
        .field("index1", &b2ChainId::index1)
        .field("world0", &b2ChainId::world0)
        .field("generation", &b2ChainId::generation);
    value_object<b2JointId>("b2JointId")
        .field("index1", &b2JointId::index1)
        .field("world0", &b2JointId::world0)
        .field("generation", &b2JointId::generation);
    value_object<b2ContactId>("b2ContactId")
        .field("index1", &b2ContactId::index1)
        .field("world0", &b2ContactId::world0)
        .field("padding", &b2ContactId::padding)
        .field("generation", &b2ContactId::generation);
    value_object<b2RayResult>("b2RayResult")
        .field("shapeId", &b2RayResult::shapeId)
        .field("point", &b2RayResult::point)
        .field("normal", &b2RayResult::normal)
        .field("fraction", &b2RayResult::fraction)
        .field("nodeVisits", &b2RayResult::nodeVisits)
        .field("leafVisits", &b2RayResult::leafVisits)
        .field("hit", &b2RayResult::hit);
    value_object<b2MotionLocks>("b2MotionLocks")
        .field("linearX", &b2MotionLocks::linearX)
        .field("linearY", &b2MotionLocks::linearY)
        .field("angularZ", &b2MotionLocks::angularZ);
    value_object<b2Profile>("b2Profile")
        .field("step", &b2Profile::step)
        .field("pairs", &b2Profile::pairs)
        .field("collide", &b2Profile::collide)
        .field("solve", &b2Profile::solve)
        .field("prepareStages", &b2Profile::prepareStages)
        .field("solveConstraints", &b2Profile::solveConstraints)
        .field("prepareConstraints", &b2Profile::prepareConstraints)
        .field("integrateVelocities", &b2Profile::integrateVelocities)
        .field("warmStart", &b2Profile::warmStart)
        .field("solveImpulses", &b2Profile::solveImpulses)
        .field("integratePositions", &b2Profile::integratePositions)
        .field("relaxImpulses", &b2Profile::relaxImpulses)
        .field("applyRestitution", &b2Profile::applyRestitution)
        .field("storeImpulses", &b2Profile::storeImpulses)
        .field("splitIslands", &b2Profile::splitIslands)
        .field("transforms", &b2Profile::transforms)
        .field("sensorHits", &b2Profile::sensorHits)
        .field("jointEvents", &b2Profile::jointEvents)
        .field("hitEvents", &b2Profile::hitEvents)
        .field("refit", &b2Profile::refit)
        .field("bullets", &b2Profile::bullets)
        .field("sleepIslands", &b2Profile::sleepIslands)
        .field("sensors", &b2Profile::sensors);
    value_object<b2Counters>("b2Counters")
        .field("bodyCount", &b2Counters::bodyCount)
        .field("shapeCount", &b2Counters::shapeCount)
        .field("contactCount", &b2Counters::contactCount)
        .field("jointCount", &b2Counters::jointCount)
        .field("islandCount", &b2Counters::islandCount)
        .field("stackUsed", &b2Counters::stackUsed)
        .field("staticTreeHeight", &b2Counters::staticTreeHeight)
        .field("treeHeight", &b2Counters::treeHeight)
        .field("byteCount", &b2Counters::byteCount)
        .field("taskCount", &b2Counters::taskCount)
        .field("colorCounts", &get_b2Counters_colorCounts, &set_b2Counters_colorCounts);
    value_object<b2SensorBeginTouchEvent>("b2SensorBeginTouchEvent")
        .field("sensorShapeId", &b2SensorBeginTouchEvent::sensorShapeId)
        .field("visitorShapeId", &b2SensorBeginTouchEvent::visitorShapeId);
    value_object<b2SensorEndTouchEvent>("b2SensorEndTouchEvent")
        .field("sensorShapeId", &b2SensorEndTouchEvent::sensorShapeId)
        .field("visitorShapeId", &b2SensorEndTouchEvent::visitorShapeId);
    value_object<b2ContactBeginTouchEvent>("b2ContactBeginTouchEvent")
        .field("shapeIdA", &b2ContactBeginTouchEvent::shapeIdA)
        .field("shapeIdB", &b2ContactBeginTouchEvent::shapeIdB)
        .field("contactId", &b2ContactBeginTouchEvent::contactId);
    value_object<b2ContactEndTouchEvent>("b2ContactEndTouchEvent")
        .field("shapeIdA", &b2ContactEndTouchEvent::shapeIdA)
        .field("shapeIdB", &b2ContactEndTouchEvent::shapeIdB)
        .field("contactId", &b2ContactEndTouchEvent::contactId);
    value_object<b2ContactHitEvent>("b2ContactHitEvent")
        .field("shapeIdA", &b2ContactHitEvent::shapeIdA)
        .field("shapeIdB", &b2ContactHitEvent::shapeIdB)
        .field("point", &b2ContactHitEvent::point)
        .field("normal", &b2ContactHitEvent::normal)
        .field("approachSpeed", &b2ContactHitEvent::approachSpeed);
    value_object<b2BodyMoveEvent>("b2BodyMoveEvent")
        .field("userData", &get_b2BodyMoveEvent_userData, &set_b2BodyMoveEvent_userData)
        .field("transform", &b2BodyMoveEvent::transform)
        .field("bodyId", &b2BodyMoveEvent::bodyId)
        .field("fellAsleep", &b2BodyMoveEvent::fellAsleep);
    value_object<b2JointEvent>("b2JointEvent")
        .field("jointId", &b2JointEvent::jointId)
        .field("userData", &get_b2JointEvent_userData, &set_b2JointEvent_userData);
    value_object<b2ContactData>("b2ContactData")
        .field("contactId", &b2ContactData::contactId)
        .field("shapeIdA", &b2ContactData::shapeIdA)
        .field("shapeIdB", &b2ContactData::shapeIdB)
        .field("manifold", &b2ContactData::manifold);

    // ---- functions ----
    function("b2GetVersion", &b2GetVersion);
    function("b2IsValidFloat", &b2IsValidFloat);
    function("b2IsValidVec2", &b2IsValidVec2);
    function("b2IsValidRotation", &b2IsValidRotation);
    function("b2IsValidTransform", &b2IsValidTransform);
    function("b2IsValidAABB", &b2IsValidAABB);
    function("b2IsValidPlane", &b2IsValidPlane);
    function("b2MinInt", &b2MinInt);
    function("b2MaxInt", &b2MaxInt);
    function("b2AbsInt", &b2AbsInt);
    function("b2ClampInt", &b2ClampInt);
    function("b2MinFloat", &b2MinFloat);
    function("b2MaxFloat", &b2MaxFloat);
    function("b2AbsFloat", &b2AbsFloat);
    function("b2ClampFloat", &b2ClampFloat);
    function("b2Atan2", &b2Atan2);
    function("b2ComputeCosSin", &b2ComputeCosSin);
    function("b2Dot", &b2Dot);
    function("b2Cross", &b2Cross);
    function("b2CrossVS", &b2CrossVS);
    function("b2CrossSV", &b2CrossSV);
    function("b2LeftPerp", &b2LeftPerp);
    function("b2RightPerp", &b2RightPerp);
    function("b2Add", &b2Add);
    function("b2Sub", &b2Sub);
    function("b2Neg", &b2Neg);
    function("b2Lerp", &b2Lerp);
    function("b2Mul", &b2Mul);
    function("b2MulSV", &b2MulSV);
    function("b2MulAdd", &b2MulAdd);
    function("b2MulSub", &b2MulSub);
    function("b2Abs", &b2Abs);
    function("b2Min", &b2Min);
    function("b2Max", &b2Max);
    function("b2Clamp", &b2Clamp);
    function("b2Length", &b2Length);
    function("b2Distance", &b2Distance);
    function("b2Normalize", &b2Normalize);
    function("b2IsNormalized", &b2IsNormalized);
    function("b2NormalizeRot", &b2NormalizeRot);
    function("b2IntegrateRotation", &b2IntegrateRotation);
    function("b2LengthSquared", &b2LengthSquared);
    function("b2DistanceSquared", &b2DistanceSquared);
    function("b2MakeRot", &b2MakeRot);
    function("b2MakeRotFromUnitVector", &b2MakeRotFromUnitVector);
    function("b2ComputeRotationBetweenUnitVectors", &b2ComputeRotationBetweenUnitVectors);
    function("b2IsNormalizedRot", &b2IsNormalizedRot);
    function("b2NLerp", &b2NLerp);
    function("b2ComputeAngularVelocity", &b2ComputeAngularVelocity);
    function("b2Rot_GetAngle", &b2Rot_GetAngle);
    function("b2Rot_GetXAxis", &b2Rot_GetXAxis);
    function("b2Rot_GetYAxis", &b2Rot_GetYAxis);
    function("b2MulRot", &b2MulRot);
    function("b2InvMulRot", &b2InvMulRot);
    function("b2RelativeAngle", &b2RelativeAngle);
    function("b2UnwindAngle", &b2UnwindAngle);
    function("b2RotateVector", &b2RotateVector);
    function("b2InvRotateVector", &b2InvRotateVector);
    function("b2TransformPoint", &b2TransformPoint);
    function("b2InvTransformPoint", &b2InvTransformPoint);
    function("b2MulTransforms", &b2MulTransforms);
    function("b2InvMulTransforms", &b2InvMulTransforms);
    function("b2MulMV", &b2MulMV);
    function("b2GetInverse22", &b2GetInverse22);
    function("b2Solve22", &b2Solve22);
    function("b2AABB_Contains", &b2AABB_Contains);
    function("b2AABB_Center", &b2AABB_Center);
    function("b2AABB_Extents", &b2AABB_Extents);
    function("b2AABB_Union", &b2AABB_Union);
    function("b2AABB_Overlaps", &b2AABB_Overlaps);
    function("b2PlaneSeparation", &b2PlaneSeparation);
    function("b2SpringDamper", &b2SpringDamper);
    function("b2SetLengthUnitsPerMeter", &b2SetLengthUnitsPerMeter);
    function("b2GetLengthUnitsPerMeter", &b2GetLengthUnitsPerMeter);
    function("b2IsValidRay", +[](const b2RayCastInput& input) -> bool { return b2IsValidRay(&input); });
    function("b2MakePolygon", +[](const b2Hull& hull, float radius) -> b2Polygon { return b2MakePolygon(&hull, radius); });
    function("b2MakeOffsetPolygon", +[](const b2Hull& hull, b2Vec2 position, b2Rot rotation) -> b2Polygon { return b2MakeOffsetPolygon(&hull, position, rotation); });
    function("b2MakeOffsetRoundedPolygon", +[](const b2Hull& hull, b2Vec2 position, b2Rot rotation, float radius) -> b2Polygon { return b2MakeOffsetRoundedPolygon(&hull, position, rotation, radius); });
    function("b2MakeSquare", &b2MakeSquare);
    function("b2MakeBox", &b2MakeBox);
    function("b2MakeRoundedBox", &b2MakeRoundedBox);
    function("b2MakeOffsetBox", &b2MakeOffsetBox);
    function("b2MakeOffsetRoundedBox", &b2MakeOffsetRoundedBox);
    function("b2TransformPolygon", +[](b2Transform transform, const b2Polygon& polygon) -> b2Polygon { return b2TransformPolygon(transform, &polygon); });
    function("b2ComputeCircleMass", +[](const b2Circle& shape, float density) -> b2MassData { return b2ComputeCircleMass(&shape, density); });
    function("b2ComputeCapsuleMass", +[](const b2Capsule& shape, float density) -> b2MassData { return b2ComputeCapsuleMass(&shape, density); });
    function("b2ComputePolygonMass", +[](const b2Polygon& shape, float density) -> b2MassData { return b2ComputePolygonMass(&shape, density); });
    function("b2ComputeCircleAABB", +[](const b2Circle& shape, b2Transform transform) -> b2AABB { return b2ComputeCircleAABB(&shape, transform); });
    function("b2ComputeCapsuleAABB", +[](const b2Capsule& shape, b2Transform transform) -> b2AABB { return b2ComputeCapsuleAABB(&shape, transform); });
    function("b2ComputePolygonAABB", +[](const b2Polygon& shape, b2Transform transform) -> b2AABB { return b2ComputePolygonAABB(&shape, transform); });
    function("b2ComputeSegmentAABB", +[](const b2Segment& shape, b2Transform transform) -> b2AABB { return b2ComputeSegmentAABB(&shape, transform); });
    function("b2PointInCircle", +[](const b2Circle& shape, b2Vec2 point) -> bool { return b2PointInCircle(&shape, point); });
    function("b2PointInCapsule", +[](const b2Capsule& shape, b2Vec2 point) -> bool { return b2PointInCapsule(&shape, point); });
    function("b2PointInPolygon", +[](const b2Polygon& shape, b2Vec2 point) -> bool { return b2PointInPolygon(&shape, point); });
    function("b2RayCastCircle", +[](const b2Circle& shape, const b2RayCastInput& input) -> b2CastOutput { return b2RayCastCircle(&shape, &input); });
    function("b2RayCastCapsule", +[](const b2Capsule& shape, const b2RayCastInput& input) -> b2CastOutput { return b2RayCastCapsule(&shape, &input); });
    function("b2RayCastSegment", +[](const b2Segment& shape, const b2RayCastInput& input, bool oneSided) -> b2CastOutput { return b2RayCastSegment(&shape, &input, oneSided); });
    function("b2RayCastPolygon", +[](const b2Polygon& shape, const b2RayCastInput& input) -> b2CastOutput { return b2RayCastPolygon(&shape, &input); });
    function("b2ShapeCastCircle", +[](const b2Circle& shape, const b2ShapeCastInput& input) -> b2CastOutput { return b2ShapeCastCircle(&shape, &input); });
    function("b2ShapeCastCapsule", +[](const b2Capsule& shape, const b2ShapeCastInput& input) -> b2CastOutput { return b2ShapeCastCapsule(&shape, &input); });
    function("b2ShapeCastSegment", +[](const b2Segment& shape, const b2ShapeCastInput& input) -> b2CastOutput { return b2ShapeCastSegment(&shape, &input); });
    function("b2ShapeCastPolygon", +[](const b2Polygon& shape, const b2ShapeCastInput& input) -> b2CastOutput { return b2ShapeCastPolygon(&shape, &input); });
    function("b2ValidateHull", +[](const b2Hull& hull) -> bool { return b2ValidateHull(&hull); });
    function("b2SegmentDistance", &b2SegmentDistance);
    function("b2ShapeCast", +[](const b2ShapeCastPairInput& input) -> b2CastOutput { return b2ShapeCast(&input); });
    function("b2GetSweepTransform", +[](const b2Sweep& sweep, float time) -> b2Transform { return b2GetSweepTransform(&sweep, time); });
    function("b2TimeOfImpact", +[](const b2TOIInput& input) -> b2TOIOutput { return b2TimeOfImpact(&input); });
    function("b2CollideCircles", +[](const b2Circle& circleA, b2Transform xfA, const b2Circle& circleB, b2Transform xfB) -> b2Manifold { return b2CollideCircles(&circleA, xfA, &circleB, xfB); });
    function("b2CollideCapsuleAndCircle", +[](const b2Capsule& capsuleA, b2Transform xfA, const b2Circle& circleB, b2Transform xfB) -> b2Manifold { return b2CollideCapsuleAndCircle(&capsuleA, xfA, &circleB, xfB); });
    function("b2CollideSegmentAndCircle", +[](const b2Segment& segmentA, b2Transform xfA, const b2Circle& circleB, b2Transform xfB) -> b2Manifold { return b2CollideSegmentAndCircle(&segmentA, xfA, &circleB, xfB); });
    function("b2CollidePolygonAndCircle", +[](const b2Polygon& polygonA, b2Transform xfA, const b2Circle& circleB, b2Transform xfB) -> b2Manifold { return b2CollidePolygonAndCircle(&polygonA, xfA, &circleB, xfB); });
    function("b2CollideCapsules", +[](const b2Capsule& capsuleA, b2Transform xfA, const b2Capsule& capsuleB, b2Transform xfB) -> b2Manifold { return b2CollideCapsules(&capsuleA, xfA, &capsuleB, xfB); });
    function("b2CollideSegmentAndCapsule", +[](const b2Segment& segmentA, b2Transform xfA, const b2Capsule& capsuleB, b2Transform xfB) -> b2Manifold { return b2CollideSegmentAndCapsule(&segmentA, xfA, &capsuleB, xfB); });
    function("b2CollidePolygonAndCapsule", +[](const b2Polygon& polygonA, b2Transform xfA, const b2Capsule& capsuleB, b2Transform xfB) -> b2Manifold { return b2CollidePolygonAndCapsule(&polygonA, xfA, &capsuleB, xfB); });
    function("b2CollidePolygons", +[](const b2Polygon& polygonA, b2Transform xfA, const b2Polygon& polygonB, b2Transform xfB) -> b2Manifold { return b2CollidePolygons(&polygonA, xfA, &polygonB, xfB); });
    function("b2CollideSegmentAndPolygon", +[](const b2Segment& segmentA, b2Transform xfA, const b2Polygon& polygonB, b2Transform xfB) -> b2Manifold { return b2CollideSegmentAndPolygon(&segmentA, xfA, &polygonB, xfB); });
    function("b2CollideChainSegmentAndCircle", +[](const b2ChainSegment& segmentA, b2Transform xfA, const b2Circle& circleB, b2Transform xfB) -> b2Manifold { return b2CollideChainSegmentAndCircle(&segmentA, xfA, &circleB, xfB); });
    function("b2StoreWorldId", &b2StoreWorldId);
    function("b2LoadWorldId", &b2LoadWorldId);
    function("b2StoreBodyId", +[](b2BodyId id) -> double { return static_cast<double>(b2StoreBodyId(id)); });
    function("b2LoadBodyId", +[](double x) -> b2BodyId { return b2LoadBodyId(toU64(x)); });
    function("b2StoreShapeId", +[](b2ShapeId id) -> double { return static_cast<double>(b2StoreShapeId(id)); });
    function("b2LoadShapeId", +[](double x) -> b2ShapeId { return b2LoadShapeId(toU64(x)); });
    function("b2StoreChainId", +[](b2ChainId id) -> double { return static_cast<double>(b2StoreChainId(id)); });
    function("b2LoadChainId", +[](double x) -> b2ChainId { return b2LoadChainId(toU64(x)); });
    function("b2StoreJointId", +[](b2JointId id) -> double { return static_cast<double>(b2StoreJointId(id)); });
    function("b2LoadJointId", +[](double x) -> b2JointId { return b2LoadJointId(toU64(x)); });
    function("b2DefaultWorldDef", +[]() -> val { return b2WorldDefToJS(b2DefaultWorldDef()); });
    function("b2DefaultBodyDef", +[]() -> val { return b2BodyDefToJS(b2DefaultBodyDef()); });
    function("b2DefaultFilter", +[]() -> val { return b2FilterToJS(b2DefaultFilter()); });
    function("b2DefaultQueryFilter", +[]() -> val { return b2QueryFilterToJS(b2DefaultQueryFilter()); });
    function("b2DefaultSurfaceMaterial", +[]() -> val { return b2SurfaceMaterialToJS(b2DefaultSurfaceMaterial()); });
    function("b2DefaultShapeDef", +[]() -> val { return b2ShapeDefToJS(b2DefaultShapeDef()); });
    function("b2DefaultChainDef", +[]() -> val { return b2ChainDefToJS(b2DefaultChainDef()); });
    function("b2DefaultDistanceJointDef", +[]() -> val { return b2DistanceJointDefToJS(b2DefaultDistanceJointDef()); });
    function("b2DefaultMotorJointDef", +[]() -> val { return b2MotorJointDefToJS(b2DefaultMotorJointDef()); });
    function("b2DefaultFilterJointDef", +[]() -> val { return b2FilterJointDefToJS(b2DefaultFilterJointDef()); });
    function("b2DefaultPrismaticJointDef", +[]() -> val { return b2PrismaticJointDefToJS(b2DefaultPrismaticJointDef()); });
    function("b2DefaultRevoluteJointDef", +[]() -> val { return b2RevoluteJointDefToJS(b2DefaultRevoluteJointDef()); });
    function("b2DefaultWeldJointDef", +[]() -> val { return b2WeldJointDefToJS(b2DefaultWeldJointDef()); });
    function("b2DefaultWheelJointDef", +[]() -> val { return b2WheelJointDefToJS(b2DefaultWheelJointDef()); });
    function("b2DefaultExplosionDef", +[]() -> val { return b2ExplosionDefToJS(b2DefaultExplosionDef()); });
    function("b2DefaultDebugDraw", +[]() -> val { return b2DebugDrawToJS(b2DefaultDebugDraw()); });
    function("b2CreateWorld", +[](val def) -> b2WorldId { b2WorldDef def_ = b2WorldDefFromJS(def); return b2CreateWorld(&def_); });
    function("b2World_IsValid", &b2World_IsValid);
    function("b2World_CastRayClosest", +[](b2WorldId worldId, b2Vec2 origin, b2Vec2 translation, val filter) -> b2RayResult { b2QueryFilter filter_ = b2QueryFilterFromJS(filter); return b2World_CastRayClosest(worldId, origin, translation, filter_); });
    function("b2World_CastMover", +[](b2WorldId worldId, const b2Capsule& mover, b2Vec2 translation, val filter) -> float { b2QueryFilter filter_ = b2QueryFilterFromJS(filter); return b2World_CastMover(worldId, &mover, translation, filter_); });
    function("b2World_EnableSleeping", &b2World_EnableSleeping);
    function("b2World_IsSleepingEnabled", &b2World_IsSleepingEnabled);
    function("b2World_EnableContinuous", &b2World_EnableContinuous);
    function("b2World_IsContinuousEnabled", &b2World_IsContinuousEnabled);
    function("b2World_SetRestitutionThreshold", &b2World_SetRestitutionThreshold);
    function("b2World_GetRestitutionThreshold", &b2World_GetRestitutionThreshold);
    function("b2World_SetHitEventThreshold", &b2World_SetHitEventThreshold);
    function("b2World_GetHitEventThreshold", &b2World_GetHitEventThreshold);
    function("b2World_SetGravity", &b2World_SetGravity);
    function("b2World_GetGravity", &b2World_GetGravity);
    function("b2World_Explode", +[](b2WorldId worldId, val explosionDef) -> void { b2ExplosionDef explosionDef_ = b2ExplosionDefFromJS(explosionDef); b2World_Explode(worldId, &explosionDef_); });
    function("b2World_SetContactTuning", &b2World_SetContactTuning);
    function("b2World_SetMaximumLinearSpeed", &b2World_SetMaximumLinearSpeed);
    function("b2World_GetMaximumLinearSpeed", &b2World_GetMaximumLinearSpeed);
    function("b2World_EnableWarmStarting", &b2World_EnableWarmStarting);
    function("b2World_IsWarmStartingEnabled", &b2World_IsWarmStartingEnabled);
    function("b2World_GetAwakeBodyCount", &b2World_GetAwakeBodyCount);
    function("b2World_GetProfile", &b2World_GetProfile);
    function("b2World_GetCounters", &b2World_GetCounters);
    function("b2World_DumpMemoryStats", &b2World_DumpMemoryStats);
    function("b2World_RebuildStaticTree", &b2World_RebuildStaticTree);
    function("b2World_EnableSpeculative", &b2World_EnableSpeculative);
    function("b2CreateBody", +[](b2WorldId worldId, val def) -> b2BodyId { b2BodyDef def_ = b2BodyDefFromJS(def); return b2CreateBody(worldId, &def_); });
    function("b2DestroyBody", &b2DestroyBody);
    function("b2Body_IsValid", &b2Body_IsValid);
    function("b2Body_GetType", &b2Body_GetType);
    function("b2Body_SetType", &b2Body_SetType);
    function("b2Body_GetPosition", &b2Body_GetPosition);
    function("b2Body_GetRotation", &b2Body_GetRotation);
    function("b2Body_GetTransform", &b2Body_GetTransform);
    function("b2Body_SetTransform", &b2Body_SetTransform);
    function("b2Body_GetLocalPoint", &b2Body_GetLocalPoint);
    function("b2Body_GetWorldPoint", &b2Body_GetWorldPoint);
    function("b2Body_GetLocalVector", &b2Body_GetLocalVector);
    function("b2Body_GetWorldVector", &b2Body_GetWorldVector);
    function("b2Body_GetLinearVelocity", &b2Body_GetLinearVelocity);
    function("b2Body_GetAngularVelocity", &b2Body_GetAngularVelocity);
    function("b2Body_SetLinearVelocity", &b2Body_SetLinearVelocity);
    function("b2Body_SetAngularVelocity", &b2Body_SetAngularVelocity);
    function("b2Body_SetTargetTransform", &b2Body_SetTargetTransform);
    function("b2Body_GetLocalPointVelocity", &b2Body_GetLocalPointVelocity);
    function("b2Body_GetWorldPointVelocity", &b2Body_GetWorldPointVelocity);
    function("b2Body_ApplyForce", &b2Body_ApplyForce);
    function("b2Body_ApplyForceToCenter", &b2Body_ApplyForceToCenter);
    function("b2Body_ApplyTorque", &b2Body_ApplyTorque);
    function("b2Body_ClearForces", &b2Body_ClearForces);
    function("b2Body_ApplyLinearImpulse", &b2Body_ApplyLinearImpulse);
    function("b2Body_ApplyLinearImpulseToCenter", &b2Body_ApplyLinearImpulseToCenter);
    function("b2Body_ApplyAngularImpulse", &b2Body_ApplyAngularImpulse);
    function("b2Body_GetMass", &b2Body_GetMass);
    function("b2Body_GetRotationalInertia", &b2Body_GetRotationalInertia);
    function("b2Body_GetLocalCenterOfMass", &b2Body_GetLocalCenterOfMass);
    function("b2Body_GetWorldCenterOfMass", &b2Body_GetWorldCenterOfMass);
    function("b2Body_SetMassData", &b2Body_SetMassData);
    function("b2Body_GetMassData", &b2Body_GetMassData);
    function("b2Body_ApplyMassFromShapes", &b2Body_ApplyMassFromShapes);
    function("b2Body_SetLinearDamping", &b2Body_SetLinearDamping);
    function("b2Body_GetLinearDamping", &b2Body_GetLinearDamping);
    function("b2Body_SetAngularDamping", &b2Body_SetAngularDamping);
    function("b2Body_GetAngularDamping", &b2Body_GetAngularDamping);
    function("b2Body_SetGravityScale", &b2Body_SetGravityScale);
    function("b2Body_GetGravityScale", &b2Body_GetGravityScale);
    function("b2Body_IsAwake", &b2Body_IsAwake);
    function("b2Body_SetAwake", &b2Body_SetAwake);
    function("b2Body_WakeTouching", &b2Body_WakeTouching);
    function("b2Body_EnableSleep", &b2Body_EnableSleep);
    function("b2Body_IsSleepEnabled", &b2Body_IsSleepEnabled);
    function("b2Body_SetSleepThreshold", &b2Body_SetSleepThreshold);
    function("b2Body_GetSleepThreshold", &b2Body_GetSleepThreshold);
    function("b2Body_IsEnabled", &b2Body_IsEnabled);
    function("b2Body_Disable", &b2Body_Disable);
    function("b2Body_Enable", &b2Body_Enable);
    function("b2Body_SetMotionLocks", &b2Body_SetMotionLocks);
    function("b2Body_GetMotionLocks", &b2Body_GetMotionLocks);
    function("b2Body_SetBullet", &b2Body_SetBullet);
    function("b2Body_IsBullet", &b2Body_IsBullet);
    function("b2Body_EnableContactEvents", &b2Body_EnableContactEvents);
    function("b2Body_EnableHitEvents", &b2Body_EnableHitEvents);
    function("b2Body_GetWorld", &b2Body_GetWorld);
    function("b2Body_GetShapeCount", &b2Body_GetShapeCount);
    function("b2Body_GetJointCount", &b2Body_GetJointCount);
    function("b2Body_GetContactCapacity", &b2Body_GetContactCapacity);
    function("b2Body_ComputeAABB", &b2Body_ComputeAABB);
    function("b2CreateCircleShape", +[](b2BodyId bodyId, val def, const b2Circle& circle) -> b2ShapeId { b2ShapeDef def_ = b2ShapeDefFromJS(def); return b2CreateCircleShape(bodyId, &def_, &circle); });
    function("b2CreateSegmentShape", +[](b2BodyId bodyId, val def, const b2Segment& segment) -> b2ShapeId { b2ShapeDef def_ = b2ShapeDefFromJS(def); return b2CreateSegmentShape(bodyId, &def_, &segment); });
    function("b2CreateCapsuleShape", +[](b2BodyId bodyId, val def, const b2Capsule& capsule) -> b2ShapeId { b2ShapeDef def_ = b2ShapeDefFromJS(def); return b2CreateCapsuleShape(bodyId, &def_, &capsule); });
    function("b2CreatePolygonShape", +[](b2BodyId bodyId, val def, const b2Polygon& polygon) -> b2ShapeId { b2ShapeDef def_ = b2ShapeDefFromJS(def); return b2CreatePolygonShape(bodyId, &def_, &polygon); });
    function("b2DestroyShape", &b2DestroyShape);
    function("b2Shape_IsValid", &b2Shape_IsValid);
    function("b2Shape_GetType", &b2Shape_GetType);
    function("b2Shape_GetBody", &b2Shape_GetBody);
    function("b2Shape_GetWorld", &b2Shape_GetWorld);
    function("b2Shape_IsSensor", &b2Shape_IsSensor);
    function("b2Shape_SetDensity", &b2Shape_SetDensity);
    function("b2Shape_GetDensity", &b2Shape_GetDensity);
    function("b2Shape_SetFriction", &b2Shape_SetFriction);
    function("b2Shape_GetFriction", &b2Shape_GetFriction);
    function("b2Shape_SetRestitution", &b2Shape_SetRestitution);
    function("b2Shape_GetRestitution", &b2Shape_GetRestitution);
    function("b2Shape_SetUserMaterial", +[](b2ShapeId shapeId, double material) -> void { b2Shape_SetUserMaterial(shapeId, toU64(material)); });
    function("b2Shape_GetUserMaterial", +[](b2ShapeId shapeId) -> double { return static_cast<double>(b2Shape_GetUserMaterial(shapeId)); });
    function("b2Shape_SetSurfaceMaterial", +[](b2ShapeId shapeId, val surfaceMaterial) -> void { b2SurfaceMaterial surfaceMaterial_ = b2SurfaceMaterialFromJS(surfaceMaterial); b2Shape_SetSurfaceMaterial(shapeId, &surfaceMaterial_); });
    function("b2Shape_GetSurfaceMaterial", +[](b2ShapeId shapeId) -> val { return b2SurfaceMaterialToJS(b2Shape_GetSurfaceMaterial(shapeId)); });
    function("b2Shape_GetFilter", +[](b2ShapeId shapeId) -> val { return b2FilterToJS(b2Shape_GetFilter(shapeId)); });
    function("b2Shape_SetFilter", +[](b2ShapeId shapeId, val filter) -> void { b2Filter filter_ = b2FilterFromJS(filter); b2Shape_SetFilter(shapeId, filter_); });
    function("b2Shape_EnableSensorEvents", &b2Shape_EnableSensorEvents);
    function("b2Shape_AreSensorEventsEnabled", &b2Shape_AreSensorEventsEnabled);
    function("b2Shape_EnableContactEvents", &b2Shape_EnableContactEvents);
    function("b2Shape_AreContactEventsEnabled", &b2Shape_AreContactEventsEnabled);
    function("b2Shape_EnablePreSolveEvents", &b2Shape_EnablePreSolveEvents);
    function("b2Shape_ArePreSolveEventsEnabled", &b2Shape_ArePreSolveEventsEnabled);
    function("b2Shape_EnableHitEvents", &b2Shape_EnableHitEvents);
    function("b2Shape_AreHitEventsEnabled", &b2Shape_AreHitEventsEnabled);
    function("b2Shape_TestPoint", &b2Shape_TestPoint);
    function("b2Shape_RayCast", +[](b2ShapeId shapeId, const b2RayCastInput& input) -> b2CastOutput { return b2Shape_RayCast(shapeId, &input); });
    function("b2Shape_GetCircle", &b2Shape_GetCircle);
    function("b2Shape_GetSegment", &b2Shape_GetSegment);
    function("b2Shape_GetChainSegment", &b2Shape_GetChainSegment);
    function("b2Shape_GetCapsule", &b2Shape_GetCapsule);
    function("b2Shape_GetPolygon", &b2Shape_GetPolygon);
    function("b2Shape_SetCircle", +[](b2ShapeId shapeId, const b2Circle& circle) -> void { b2Shape_SetCircle(shapeId, &circle); });
    function("b2Shape_SetCapsule", +[](b2ShapeId shapeId, const b2Capsule& capsule) -> void { b2Shape_SetCapsule(shapeId, &capsule); });
    function("b2Shape_SetSegment", +[](b2ShapeId shapeId, const b2Segment& segment) -> void { b2Shape_SetSegment(shapeId, &segment); });
    function("b2Shape_SetPolygon", +[](b2ShapeId shapeId, const b2Polygon& polygon) -> void { b2Shape_SetPolygon(shapeId, &polygon); });
    function("b2Shape_GetParentChain", &b2Shape_GetParentChain);
    function("b2Shape_GetContactCapacity", &b2Shape_GetContactCapacity);
    function("b2Shape_GetSensorCapacity", &b2Shape_GetSensorCapacity);
    function("b2Shape_GetAABB", &b2Shape_GetAABB);
    function("b2Shape_ComputeMassData", &b2Shape_ComputeMassData);
    function("b2Shape_GetClosestPoint", &b2Shape_GetClosestPoint);
    function("b2Shape_ApplyWind", &b2Shape_ApplyWind);
    function("b2DestroyChain", &b2DestroyChain);
    function("b2Chain_GetWorld", &b2Chain_GetWorld);
    function("b2Chain_GetSegmentCount", &b2Chain_GetSegmentCount);
    function("b2Chain_SetSurfaceMaterial", +[](b2ChainId chainId, val material, int materialIndex) -> void { b2SurfaceMaterial material_ = b2SurfaceMaterialFromJS(material); b2Chain_SetSurfaceMaterial(chainId, &material_, materialIndex); });
    function("b2Chain_GetSurfaceMaterial", +[](b2ChainId chainId, int materialIndex) -> val { return b2SurfaceMaterialToJS(b2Chain_GetSurfaceMaterial(chainId, materialIndex)); });
    function("b2Chain_IsValid", &b2Chain_IsValid);
    function("b2DestroyJoint", &b2DestroyJoint);
    function("b2Joint_IsValid", &b2Joint_IsValid);
    function("b2Joint_GetType", &b2Joint_GetType);
    function("b2Joint_GetBodyA", &b2Joint_GetBodyA);
    function("b2Joint_GetBodyB", &b2Joint_GetBodyB);
    function("b2Joint_GetWorld", &b2Joint_GetWorld);
    function("b2Joint_SetLocalFrameA", &b2Joint_SetLocalFrameA);
    function("b2Joint_GetLocalFrameA", &b2Joint_GetLocalFrameA);
    function("b2Joint_SetLocalFrameB", &b2Joint_SetLocalFrameB);
    function("b2Joint_GetLocalFrameB", &b2Joint_GetLocalFrameB);
    function("b2Joint_SetCollideConnected", &b2Joint_SetCollideConnected);
    function("b2Joint_GetCollideConnected", &b2Joint_GetCollideConnected);
    function("b2Joint_WakeBodies", &b2Joint_WakeBodies);
    function("b2Joint_GetConstraintForce", &b2Joint_GetConstraintForce);
    function("b2Joint_GetConstraintTorque", &b2Joint_GetConstraintTorque);
    function("b2Joint_GetLinearSeparation", &b2Joint_GetLinearSeparation);
    function("b2Joint_GetAngularSeparation", &b2Joint_GetAngularSeparation);
    function("b2Joint_SetConstraintTuning", &b2Joint_SetConstraintTuning);
    function("b2Joint_SetForceThreshold", &b2Joint_SetForceThreshold);
    function("b2Joint_GetForceThreshold", &b2Joint_GetForceThreshold);
    function("b2Joint_SetTorqueThreshold", &b2Joint_SetTorqueThreshold);
    function("b2Joint_GetTorqueThreshold", &b2Joint_GetTorqueThreshold);
    function("b2CreateDistanceJoint", +[](b2WorldId worldId, val def) -> b2JointId { b2DistanceJointDef def_ = b2DistanceJointDefFromJS(def); return b2CreateDistanceJoint(worldId, &def_); });
    function("b2DistanceJoint_SetLength", &b2DistanceJoint_SetLength);
    function("b2DistanceJoint_GetLength", &b2DistanceJoint_GetLength);
    function("b2DistanceJoint_EnableSpring", &b2DistanceJoint_EnableSpring);
    function("b2DistanceJoint_IsSpringEnabled", &b2DistanceJoint_IsSpringEnabled);
    function("b2DistanceJoint_SetSpringForceRange", &b2DistanceJoint_SetSpringForceRange);
    function("b2DistanceJoint_SetSpringHertz", &b2DistanceJoint_SetSpringHertz);
    function("b2DistanceJoint_SetSpringDampingRatio", &b2DistanceJoint_SetSpringDampingRatio);
    function("b2DistanceJoint_GetSpringHertz", &b2DistanceJoint_GetSpringHertz);
    function("b2DistanceJoint_GetSpringDampingRatio", &b2DistanceJoint_GetSpringDampingRatio);
    function("b2DistanceJoint_EnableLimit", &b2DistanceJoint_EnableLimit);
    function("b2DistanceJoint_IsLimitEnabled", &b2DistanceJoint_IsLimitEnabled);
    function("b2DistanceJoint_SetLengthRange", &b2DistanceJoint_SetLengthRange);
    function("b2DistanceJoint_GetMinLength", &b2DistanceJoint_GetMinLength);
    function("b2DistanceJoint_GetMaxLength", &b2DistanceJoint_GetMaxLength);
    function("b2DistanceJoint_GetCurrentLength", &b2DistanceJoint_GetCurrentLength);
    function("b2DistanceJoint_EnableMotor", &b2DistanceJoint_EnableMotor);
    function("b2DistanceJoint_IsMotorEnabled", &b2DistanceJoint_IsMotorEnabled);
    function("b2DistanceJoint_SetMotorSpeed", &b2DistanceJoint_SetMotorSpeed);
    function("b2DistanceJoint_GetMotorSpeed", &b2DistanceJoint_GetMotorSpeed);
    function("b2DistanceJoint_SetMaxMotorForce", &b2DistanceJoint_SetMaxMotorForce);
    function("b2DistanceJoint_GetMaxMotorForce", &b2DistanceJoint_GetMaxMotorForce);
    function("b2DistanceJoint_GetMotorForce", &b2DistanceJoint_GetMotorForce);
    function("b2CreateMotorJoint", +[](b2WorldId worldId, val def) -> b2JointId { b2MotorJointDef def_ = b2MotorJointDefFromJS(def); return b2CreateMotorJoint(worldId, &def_); });
    function("b2MotorJoint_SetLinearVelocity", &b2MotorJoint_SetLinearVelocity);
    function("b2MotorJoint_GetLinearVelocity", &b2MotorJoint_GetLinearVelocity);
    function("b2MotorJoint_SetAngularVelocity", &b2MotorJoint_SetAngularVelocity);
    function("b2MotorJoint_GetAngularVelocity", &b2MotorJoint_GetAngularVelocity);
    function("b2MotorJoint_SetMaxVelocityForce", &b2MotorJoint_SetMaxVelocityForce);
    function("b2MotorJoint_GetMaxVelocityForce", &b2MotorJoint_GetMaxVelocityForce);
    function("b2MotorJoint_SetMaxVelocityTorque", &b2MotorJoint_SetMaxVelocityTorque);
    function("b2MotorJoint_GetMaxVelocityTorque", &b2MotorJoint_GetMaxVelocityTorque);
    function("b2MotorJoint_SetLinearHertz", &b2MotorJoint_SetLinearHertz);
    function("b2MotorJoint_GetLinearHertz", &b2MotorJoint_GetLinearHertz);
    function("b2MotorJoint_SetLinearDampingRatio", &b2MotorJoint_SetLinearDampingRatio);
    function("b2MotorJoint_GetLinearDampingRatio", &b2MotorJoint_GetLinearDampingRatio);
    function("b2MotorJoint_SetAngularHertz", &b2MotorJoint_SetAngularHertz);
    function("b2MotorJoint_GetAngularHertz", &b2MotorJoint_GetAngularHertz);
    function("b2MotorJoint_SetAngularDampingRatio", &b2MotorJoint_SetAngularDampingRatio);
    function("b2MotorJoint_GetAngularDampingRatio", &b2MotorJoint_GetAngularDampingRatio);
    function("b2MotorJoint_SetMaxSpringForce", &b2MotorJoint_SetMaxSpringForce);
    function("b2MotorJoint_GetMaxSpringForce", &b2MotorJoint_GetMaxSpringForce);
    function("b2MotorJoint_SetMaxSpringTorque", &b2MotorJoint_SetMaxSpringTorque);
    function("b2MotorJoint_GetMaxSpringTorque", &b2MotorJoint_GetMaxSpringTorque);
    function("b2CreateFilterJoint", +[](b2WorldId worldId, val def) -> b2JointId { b2FilterJointDef def_ = b2FilterJointDefFromJS(def); return b2CreateFilterJoint(worldId, &def_); });
    function("b2CreatePrismaticJoint", +[](b2WorldId worldId, val def) -> b2JointId { b2PrismaticJointDef def_ = b2PrismaticJointDefFromJS(def); return b2CreatePrismaticJoint(worldId, &def_); });
    function("b2PrismaticJoint_EnableSpring", &b2PrismaticJoint_EnableSpring);
    function("b2PrismaticJoint_IsSpringEnabled", &b2PrismaticJoint_IsSpringEnabled);
    function("b2PrismaticJoint_SetSpringHertz", &b2PrismaticJoint_SetSpringHertz);
    function("b2PrismaticJoint_GetSpringHertz", &b2PrismaticJoint_GetSpringHertz);
    function("b2PrismaticJoint_SetSpringDampingRatio", &b2PrismaticJoint_SetSpringDampingRatio);
    function("b2PrismaticJoint_GetSpringDampingRatio", &b2PrismaticJoint_GetSpringDampingRatio);
    function("b2PrismaticJoint_SetTargetTranslation", &b2PrismaticJoint_SetTargetTranslation);
    function("b2PrismaticJoint_GetTargetTranslation", &b2PrismaticJoint_GetTargetTranslation);
    function("b2PrismaticJoint_EnableLimit", &b2PrismaticJoint_EnableLimit);
    function("b2PrismaticJoint_IsLimitEnabled", &b2PrismaticJoint_IsLimitEnabled);
    function("b2PrismaticJoint_GetLowerLimit", &b2PrismaticJoint_GetLowerLimit);
    function("b2PrismaticJoint_GetUpperLimit", &b2PrismaticJoint_GetUpperLimit);
    function("b2PrismaticJoint_SetLimits", &b2PrismaticJoint_SetLimits);
    function("b2PrismaticJoint_EnableMotor", &b2PrismaticJoint_EnableMotor);
    function("b2PrismaticJoint_IsMotorEnabled", &b2PrismaticJoint_IsMotorEnabled);
    function("b2PrismaticJoint_SetMotorSpeed", &b2PrismaticJoint_SetMotorSpeed);
    function("b2PrismaticJoint_GetMotorSpeed", &b2PrismaticJoint_GetMotorSpeed);
    function("b2PrismaticJoint_SetMaxMotorForce", &b2PrismaticJoint_SetMaxMotorForce);
    function("b2PrismaticJoint_GetMaxMotorForce", &b2PrismaticJoint_GetMaxMotorForce);
    function("b2PrismaticJoint_GetMotorForce", &b2PrismaticJoint_GetMotorForce);
    function("b2PrismaticJoint_GetTranslation", &b2PrismaticJoint_GetTranslation);
    function("b2PrismaticJoint_GetSpeed", &b2PrismaticJoint_GetSpeed);
    function("b2CreateRevoluteJoint", +[](b2WorldId worldId, val def) -> b2JointId { b2RevoluteJointDef def_ = b2RevoluteJointDefFromJS(def); return b2CreateRevoluteJoint(worldId, &def_); });
    function("b2RevoluteJoint_EnableSpring", &b2RevoluteJoint_EnableSpring);
    function("b2RevoluteJoint_IsSpringEnabled", &b2RevoluteJoint_IsSpringEnabled);
    function("b2RevoluteJoint_SetSpringHertz", &b2RevoluteJoint_SetSpringHertz);
    function("b2RevoluteJoint_GetSpringHertz", &b2RevoluteJoint_GetSpringHertz);
    function("b2RevoluteJoint_SetSpringDampingRatio", &b2RevoluteJoint_SetSpringDampingRatio);
    function("b2RevoluteJoint_GetSpringDampingRatio", &b2RevoluteJoint_GetSpringDampingRatio);
    function("b2RevoluteJoint_SetTargetAngle", &b2RevoluteJoint_SetTargetAngle);
    function("b2RevoluteJoint_GetTargetAngle", &b2RevoluteJoint_GetTargetAngle);
    function("b2RevoluteJoint_GetAngle", &b2RevoluteJoint_GetAngle);
    function("b2RevoluteJoint_EnableLimit", &b2RevoluteJoint_EnableLimit);
    function("b2RevoluteJoint_IsLimitEnabled", &b2RevoluteJoint_IsLimitEnabled);
    function("b2RevoluteJoint_GetLowerLimit", &b2RevoluteJoint_GetLowerLimit);
    function("b2RevoluteJoint_GetUpperLimit", &b2RevoluteJoint_GetUpperLimit);
    function("b2RevoluteJoint_SetLimits", &b2RevoluteJoint_SetLimits);
    function("b2RevoluteJoint_EnableMotor", &b2RevoluteJoint_EnableMotor);
    function("b2RevoluteJoint_IsMotorEnabled", &b2RevoluteJoint_IsMotorEnabled);
    function("b2RevoluteJoint_SetMotorSpeed", &b2RevoluteJoint_SetMotorSpeed);
    function("b2RevoluteJoint_GetMotorSpeed", &b2RevoluteJoint_GetMotorSpeed);
    function("b2RevoluteJoint_GetMotorTorque", &b2RevoluteJoint_GetMotorTorque);
    function("b2RevoluteJoint_SetMaxMotorTorque", &b2RevoluteJoint_SetMaxMotorTorque);
    function("b2RevoluteJoint_GetMaxMotorTorque", &b2RevoluteJoint_GetMaxMotorTorque);
    function("b2CreateWeldJoint", +[](b2WorldId worldId, val def) -> b2JointId { b2WeldJointDef def_ = b2WeldJointDefFromJS(def); return b2CreateWeldJoint(worldId, &def_); });
    function("b2WeldJoint_SetLinearHertz", &b2WeldJoint_SetLinearHertz);
    function("b2WeldJoint_GetLinearHertz", &b2WeldJoint_GetLinearHertz);
    function("b2WeldJoint_SetLinearDampingRatio", &b2WeldJoint_SetLinearDampingRatio);
    function("b2WeldJoint_GetLinearDampingRatio", &b2WeldJoint_GetLinearDampingRatio);
    function("b2WeldJoint_SetAngularHertz", &b2WeldJoint_SetAngularHertz);
    function("b2WeldJoint_GetAngularHertz", &b2WeldJoint_GetAngularHertz);
    function("b2WeldJoint_SetAngularDampingRatio", &b2WeldJoint_SetAngularDampingRatio);
    function("b2WeldJoint_GetAngularDampingRatio", &b2WeldJoint_GetAngularDampingRatio);
    function("b2CreateWheelJoint", +[](b2WorldId worldId, val def) -> b2JointId { b2WheelJointDef def_ = b2WheelJointDefFromJS(def); return b2CreateWheelJoint(worldId, &def_); });
    function("b2WheelJoint_EnableSpring", &b2WheelJoint_EnableSpring);
    function("b2WheelJoint_IsSpringEnabled", &b2WheelJoint_IsSpringEnabled);
    function("b2WheelJoint_SetSpringHertz", &b2WheelJoint_SetSpringHertz);
    function("b2WheelJoint_GetSpringHertz", &b2WheelJoint_GetSpringHertz);
    function("b2WheelJoint_SetSpringDampingRatio", &b2WheelJoint_SetSpringDampingRatio);
    function("b2WheelJoint_GetSpringDampingRatio", &b2WheelJoint_GetSpringDampingRatio);
    function("b2WheelJoint_EnableLimit", &b2WheelJoint_EnableLimit);
    function("b2WheelJoint_IsLimitEnabled", &b2WheelJoint_IsLimitEnabled);
    function("b2WheelJoint_GetLowerLimit", &b2WheelJoint_GetLowerLimit);
    function("b2WheelJoint_GetUpperLimit", &b2WheelJoint_GetUpperLimit);
    function("b2WheelJoint_SetLimits", &b2WheelJoint_SetLimits);
    function("b2WheelJoint_EnableMotor", &b2WheelJoint_EnableMotor);
    function("b2WheelJoint_IsMotorEnabled", &b2WheelJoint_IsMotorEnabled);
    function("b2WheelJoint_SetMotorSpeed", &b2WheelJoint_SetMotorSpeed);
    function("b2WheelJoint_GetMotorSpeed", &b2WheelJoint_GetMotorSpeed);
    function("b2WheelJoint_SetMaxMotorTorque", &b2WheelJoint_SetMaxMotorTorque);
    function("b2WheelJoint_GetMaxMotorTorque", &b2WheelJoint_GetMaxMotorTorque);
    function("b2WheelJoint_GetMotorTorque", &b2WheelJoint_GetMotorTorque);
    function("b2Contact_IsValid", &b2Contact_IsValid);
    function("b2Contact_GetData", &b2Contact_GetData);
}
